const ProcurementField = {
  supplier_id: "supplier_id",
  store_id: "store_id",
  note: "note",
  supplier_phone: "supplier_phone",
  supplier: "supplier",
  file: "file",
  po_code: "po_code",
};

export const ProcurementLineItemField = {
  code: "code",
  reference: "reference",
  store_id: "store_id",
  expect_receipt_date: "expect_receipt_date",
  procurement_items: "procurement_items",
  purchase_order_code: "purchase_order_code",
  status: "status",
  note: "note",
  purchase_order_reference: "purchase_order_reference",
  purchase_order_supplier_code: "purchase_order_supplier_code",
  supplier: "supplier",
  store: "store",
  product_code: "product_code",
  product_name: "product_name",
  sku: "sku",
  variant: "variant",
  barcode: "barcode",
  real_quantity: "real_quantity",
  price: "price",
  amount: "amount",
  created_by: "create_by",
  created_name: "created_name",
  created_date: "created_date",
  actived_date: "actived_date",
  actived_by: "actived_by",
  activated_by: "activated_by",
  stock_in_date: "stock_in_date",
  stock_in_by: "stock_in_by",
  is_cancelled: "is_cancelled",
  purchase_order_merchandiser: "purchase_order_merchandiser",
  purchase_order_designer: "purchase_order_designer",
};

const ProcurementExportLineItemField = {
  [ProcurementLineItemField.code]: "Mã phiếu nhập kho",
  [ProcurementLineItemField.purchase_order_code]: "Mã đơn đặt hàng",
  [ProcurementLineItemField.purchase_order_reference]: "Mã tham chiếu",
  [ProcurementLineItemField.purchase_order_supplier_code]: "Mã nhà cung cấp",
  [ProcurementLineItemField.status]: "Trạng thái",
  [ProcurementLineItemField.supplier]: "Nhà cung cấp",
  [ProcurementLineItemField.store]: "Kho hàng",
  [ProcurementLineItemField.product_code]: "Mã sản phẩm cha",
  [ProcurementLineItemField.product_name]: "Tên sản phẩm cha",
  [ProcurementLineItemField.sku]: "Mã sản phẩm",
  [ProcurementLineItemField.variant]: "Sản phẩm",
  [ProcurementLineItemField.barcode]: "Mã vạch",
  [ProcurementLineItemField.real_quantity]: "Số lượng nhập",
  [ProcurementLineItemField.price]: "Giá nhập",
  [ProcurementLineItemField.amount]: "Thành tiền",
  [ProcurementLineItemField.created_date]: "Ngày tạo",
  [ProcurementLineItemField.created_name]: "Người tạo",
  [ProcurementLineItemField.stock_in_date]: "Ngày nhận",
  [ProcurementLineItemField.stock_in_by]: "Người nhận",
  [ProcurementLineItemField.purchase_order_merchandiser]: "Merchandiser",
  [ProcurementLineItemField.purchase_order_designer]: "Người thiết kế",
  [ProcurementLineItemField.note]: "Ghi chú",
};

export { ProcurementField, ProcurementExportLineItemField };
