import { OrderDiscountRequest } from "./OrderDiscountRequest";
import { OrderLineItemRequest } from "./OrderLineItemRequest";
import { OrderPaymentRequest } from "./OrderPaymentRequest";

export interface OrderRequest {
  company_id: number,
  store_id: number,
  store: string,
  status: string,
  price_type: string,
  tax_treatment: string,
  source_id: number,
  note: string,
  tags: string,
  customer_note: string,
  sale_note: string,
  account_code: string,
  account: string,
  source: string,
  assignee_code: string,
  assignee: string,
  channel_id: number,
  channel: string,
  customer_id: number,
  billing_address_id?: number,
  shipping_address_id?: number,
  fulfillment_status: string,
  packed_status: string,
  received_Status: string,
  payment_status: string,
  return_status: string,
  total_line_amount_after_line_discount: number,
  total: number,
  order_discount_rate: number,
  order_discount_value: number,
  discount_reason: string,
  total_discount: number,
  total_tax: string,
  finalized_account_code: string,
  cancel_account_code: string,
  finish_account_code: string,
  finalized_on: string,
  cancelled_on: string,
  finished_on: string,
  currency: string,
  items: Array<OrderLineItemRequest>,
  discounts: Array<OrderDiscountRequest>,
  payments: Array<OrderPaymentRequest>,
}