import { render, waitFor } from "@testing-library/react";
import { BrowserRouter, Router } from "react-router-dom";
import { handleFixWindowMatchMediaTest } from "screens/order-online/utils/test.utils";
import UpdateCustomerCard from "./update-customer-card";

handleFixWindowMatchMediaTest();

const orderDetailDataTest: any = {
  id: 21905310,
  code: "SO021905310",
  version: 1,
  created_by: "YD99999",
  created_name: "Quản trị viên",
  created_date: "2022-10-15T06:11:49Z",
  updated_by: "YD99999",
  updated_name: "Quản trị viên",
  updated_date: "2022-10-15T06:11:49Z",
  reference_code: "",
  company_id: 1,
  company: "Công ty cổ phần thời trang YODY",
  store_id: 2,
  store_code: "YDVNHTH01",
  store: "YODY Đức Thọ",
  store_phone_number: "18002086",
  store_full_address: "Từ Ô, Tân Trào, Thanh Miện District, Hai Duong, Vietnam",
  status: "finalized",
  price_type: "retail_price",
  tax_treatment: "inclusive",
  source_id: 110,
  source_code: "SC000055",
  source: "CNTT Hà Nội",
  note: "",
  tags: "",
  payment_method_id: null,
  payment_method_code: null,
  payment_method: null,
  expected_payment_method_id: null,
  expected_delivery_provider_id: null,
  expected_delivery_type: null,
  customer_note: "",
  sale_note: null,
  account_code: "YD99999",
  account: "Quản trị viên",
  marketer_code: "YD15552",
  marketer: "Vũ Xuân Tú",
  coordinator_code: null,
  coordinator: null,
  assignee_code: "YD99999",
  assignee: "Quản trị viên",
  channel_id: 13,
  channel_code: "ADMIN",
  channel: "Admin",
  customer_id: 3014155,
  customer: "Chiến hoàn ",
  customer_phone_number: "0988309621",
  customer_email: null,
  fulfillment_status: "unshipped",
  packed_status: null,
  received_status: null,
  payment_status: "paid",
  return_status: "unreturned",
  total_line_amount_after_line_discount: 29000,
  total: 51200,
  order_discount_rate: null,
  order_discount_value: null,
  discount_reason: null,
  total_discount: 0,
  total_tax: null,
  finalized_account_code: "YD99999",
  cancel_account_code: null,
  finish_account_code: null,
  finalized_on: "2022-10-15T06:11:49.000+00:00",
  cancelled_on: null,
  finished_on: null,
  items: [
    {
      id: 231366,
      code: "393778f7-22f4-4968-a5f4-735c07aebf59",
      version: 1,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-10-15T06:11:49Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-15T06:11:49Z",
      order_line_item_id: null,
      sku: "APM3055-XLO-M",
      variant_id: 65392,
      variant: "Áo nam Music is my Life - Xanh lơ - M",
      product_id: 16004,
      product: "Áo nam Music is my Life",
      product_code: "APM3055",
      variant_barcode: "2000111271847",
      product_type: "normal",
      quantity: 1,
      price: 29000,
      amount: 29000,
      discount_items: [],
      note: "",
      variant_image: "",
      unit: "piece",
      warranty: null,
      tax_rate: 0,
      tax_include: null,
      is_composite: null,
      line_amount_after_line_discount: 29000,
      discount_rate: 0,
      discount_value: 0,
      discount_amount: 0,
      position: 1,
      weight: 200,
      weight_unit: "g",
      type: "normal",
    },
  ],
  discounts: [],
  pre_payments: null,
  payments: [
    {
      id: 129512,
      code: "88a3b0a9-cd3d-49a6-929c-ed1a0eda6521",
      version: 1,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-10-15T06:11:49Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-15T06:11:49Z",
      fulfillment_id: null,
      payment_method_id: 0,
      payment_method_code: "exchange",
      payment_method: "Hàng đổi",
      amount: 51200,
      reference: "",
      source: "",
      paid_amount: 51200,
      return_amount: 0,
      status: "paid",
      customer_id: null,
      type: "",
      invoice_id: null,
      note: null,
      point: null,
      bank_account_id: null,
      bank_account_number: null,
      bank_account_holder: null,
      bank_code: null,
      bank_name: null,
      ref_transaction_code: "",
      pay_url: null,
      short_link: null,
      expired_at: null,
    },
  ],
  fulfillments: [
    {
      id: 150826,
      code: "FM000150826",
      version: 1,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-10-15T06:11:49Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-15T06:11:49Z",
      order_id: 21905310,
      account_code: "YD99999",
      assignee_code: "YD99999",
      delivery_type: "",
      status: "unshipped",
      partner_status: null,
      shipment: {
        id: 74948,
        code: "2e8a44a2-3a61-48b6-b57e-f25613277347",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-15T06:11:49Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-15T06:11:49Z",
        delivery_service_provider_id: null,
        delivery_service_provider_code: null,
        delivery_service_provider_name: null,
        delivery_service_provider_type: "employee",
        delivery_transport_type: "",
        delivery_service_note: null,
        handover_id: null,
        service: "",
        who_paid: null,
        fee_type: "",
        fee_base_on: "",
        delivery_fee: null,
        reference_status: "",
        reference_status_explanation: "",
        cancel_reason: "",
        tracking_code: "",
        tracking_url: "",
        received_date: null,
        expected_received_date: null,
        shipping_fee_paid_to_three_pls: null,
        sender_address_id: null,
        sender_address: null,
        requirements: "open_try",
        requirements_name: null,
        note_to_shipper: "",
        fulfillment_id: 150826,
        cod: 0,
        shipper_code: "YD777777",
        shipper_name: "Lê Văn Chiến",
        pushing_note: null,
        pushing_status: null,
        shipping_address: null,
        office_time: null,
        shipper_phone: "0392848262",
        recipient_sort_code: null,
        info_shipper: "YD777777 - Lê Văn Chiến - 0392848262",
        type_shipment: null,
      },
      billing_address_id: null,
      items: [
        {
          id: 187631,
          code: "49ca6420-55b6-4381-90a3-3815a10b4c56",
          version: 1,
          created_by: "YD99999",
          created_name: "Quản trị viên",
          created_date: "2022-10-15T06:11:49Z",
          updated_by: "YD99999",
          updated_name: "Quản trị viên",
          updated_date: "2022-10-15T06:11:49Z",
          order_line_item_id: 231366,
          product_id: 16004,
          product: "Áo nam Music is my Life",
          product_code: "APM3055",
          variant_id: 65392,
          variant: "Áo nam Music is my Life - Xanh lơ - M",
          order_line_item_note: null,
          quantity: 1,
          base_price: null,
          discount_rate: 0,
          discount_value: 0,
          tax_type_id: null,
          tax_rate: 0,
          line_amount: null,
          line_discount_amount: null,
          line_amount_after_line_discount: 29000,
          weight: 200,
          weight_unit: "g",
          sku: "APM3055-XLO-M",
          variant_barcode: "2000111271847",
          unit: "piece",
        },
      ],
      stock_location_id: 2,
      returned_store_id: 2,
      payment_status: "paid",
      total: 51200,
      total_tax: null,
      total_discount: 0,
      total_quantity: 1,
      stock_out_account_code: null,
      receive_account_code: null,
      cancel_account_code: null,
      receive_cancellation_account_code: null,
      payments: null,
      picked_on: null,
      packed_on: null,
      shipped_on: null,
      export_on: null,
      received_on: null,
      cancel_date: null,
      return_status: "unreturned",
      receive_cancellation_on: null,
      status_before_cancellation: null,
      discount_rate: null,
      discount_value: null,
      discount_amount: null,
      total_line_amount_after_line_discount: 29000,
      returning_on: null,
      sub_reason_name: null,
      sub_reason_detail_id: null,
      sub_reason_id: null,
      reason_id: null,
      reason_name: null,
      sub_reason_detail_name: null,
    },
  ],
  currency: "VND",
  billing_address: {
    id: 29235,
    code: "4b7705da-5223-42bc-ac54-abc800f85b96",
    version: 1,
    created_by: "YD99999",
    created_name: "Quản trị viên",
    created_date: "2022-10-15T06:11:49Z",
    updated_by: "YD99999",
    updated_name: "Quản trị viên",
    updated_date: "2022-10-15T06:11:49Z",
    name: "Chiến",
    email: null,
    phone: "840988309621",
    country: null,
    city: "Hà Nội",
    district: "Quận Đống Đa",
    ward: "Hà Nội, Quận Đống Đa, Phường Phương Liên",
    zip_code: "",
    full_address:
      "42a ngõ 249 phố chợ khâm Thiên,Hà Nội, Quận Đống Đa, Phường Phương Liên,Quận Đống Đa,Hà Nội",
    buyer: null,
    tax_code: null,
    note: null,
    order_id: 21905310,
    contract: false,
  },
  shipping_address: {
    id: 87261,
    code: "8bb884c1-f27e-4c20-879b-3e04edfecb0c",
    version: 1,
    created_by: "YD99999",
    created_name: "Quản trị viên",
    created_date: "2022-10-15T06:11:49Z",
    updated_by: "YD99999",
    updated_name: "Quản trị viên",
    updated_date: "2022-10-15T06:11:49Z",
    name: "Chiến",
    email: null,
    phone: "0988309621",
    second_phone: null,
    country: null,
    city_id: 1,
    city: "TP. Hà Nội",
    district_id: 2,
    district: "Quận Tây Hồ",
    ward_id: 12,
    ward: "Phường Bưởi",
    zip_code: "",
    full_address: "42a ngõ 249 phố chợ khâm Thiên,Phường Phương Liên,Quận Đống Đa,Hà Nội",
    channel: null,
  },
  shipping_fee_informed_to_customer: 22200,
  url: "",
  sub_status_id: 2,
  sub_status_code: "awaiting_coordinator_confirmation",
  sub_status: "Mới",
  order_returns: [],
  accumulate_point: null,
  linked_order_code: null,
  ecommerce_shop_id: null,
  ecommerce_shop_name: null,
  order_migration_id: null,
  created_on: "2022-10-15T06:11:49.000+00:00",
  campaign_id: null,
  utm_tracking: null,
  export_bill: false,
  migration_note: null,
  atomic_migration: false,
  actual_quantity: 1,
  uniform: true,
  sub_reason_name: null,
  automatic_discount: true,
  sub_reason_id: null,
  reason_id: null,
  reason_name: null,
};
const customerDetailDataTest: any = {
  id: 3014155,
  code: "CU003014155",
  version: 5,
  created_by: "",
  created_name: "admin",
  created_date: "2022-10-06T06:18:01Z",
  updated_by: "YD99999",
  updated_name: "Quản trị viên",
  updated_date: "2022-10-06T06:18:01Z",
  full_name: "Chiến hoàn ",
  phone: "0988309621",
  email: null,
  customer_group_id: 1,
  customer_group: "CÔNG NHÂN",
  customer_type_id: null,
  customer_type: null,
  company_id: null,
  company: null,
  website: null,
  description: null,
  customer_level_id: 22,
  customer_level: "SIÊU VIP",
  status: "active",
  wedding_date: null,
  birthday: "2022-05-20T17:00:00Z",
  gender: "male",
  responsible_staff_code: null,
  responsible_staff: null,
  tags: null,
  notes: [],
  tax_code: null,
  country_id: 233,
  country: null,
  city_id: 1,
  city: "TP. Hà Nội",
  district_id: 6,
  district: "Quận Đống Đa",
  ward_id: 72,
  ward: "Phường Cát Linh",
  zip_code: null,
  full_address: "hải dương",
  card_number: null,
  channel: null,
  channel_id: null,
  channel_code: null,
  source: null,
  source_id: null,
  source_code: null,
  billing_addresses: [
    {
      id: 15933,
      code: "maTgvz2ohqB3",
      version: 1,
      created_by: "",
      created_name: "admin",
      created_date: "2022-05-18T18:10:47Z",
      updated_by: "",
      updated_name: "admin",
      updated_date: "2022-05-18T18:10:47Z",
      name: "Chiến",
      email: null,
      phone: "840988309621",
      country_id: null,
      country: null,
      city_id: null,
      city: "Hà Nội",
      district_id: null,
      district: "Quận Đống Đa",
      ward_id: null,
      ward: "Hà Nội, Quận Đống Đa, Phường Phương Liên",
      zip_code: "",
      full_address:
        "42a ngõ 249 phố chợ khâm Thiên,Hà Nội, Quận Đống Đa, Phường Phương Liên,Quận Đống Đa,Hà Nội",
      tax_code: null,
      buyer: null,
      default: true,
    },
  ],
  shipping_addresses: [
    {
      id: 16465,
      code: "kL5XwJXgcukV",
      version: 9,
      created_by: "",
      created_name: "admin",
      created_date: "2022-05-18T18:10:47Z",
      updated_by: "",
      updated_name: "admin",
      updated_date: "2022-10-06T06:18:01Z",
      name: "Chiến",
      email: null,
      phone: "0988309621",
      country_id: null,
      country: null,
      city_id: 1,
      city: "TP. Hà Nội",
      district_id: 2,
      district: "Quận Tây Hồ",
      ward_id: 12,
      ward: "Phường Bưởi",
      zip_code: "",
      full_address: "42a ngõ 249 phố chợ khâm Thiên,Phường Phương Liên,Quận Đống Đa,Hà Nội",
      default: true,
    },
    {
      id: 51591,
      code: "eOeMyAxwrfLB",
      version: 7,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-08-11T02:30:01Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-06T06:17:27Z",
      name: "Mẫu in bán lẻ",
      email: null,
      phone: "0392848261",
      country_id: 233,
      country: "VIETNAM",
      city_id: 1,
      city: "TP. Hà Nội",
      district_id: 1,
      district: "Quận Thanh Xuân",
      ward_id: 1,
      ward: "Phường Hạ Đình",
      zip_code: null,
      full_address: "abcv",
      default: false,
    },
  ],
  contacts: [],
  report: {
    total_finished_order: 4943,
    total_returned_order: 81,
    total_paid_amount: 3895619840,
    total_refunded_amount: 30215562,
    remain_amount_to_level_up: null,
    average_order_value: 788108.4,
    first_order_time: "2022-05-18T18:11:22Z",
    last_order_time: "2022-10-08T03:08:11Z",
    number_of_days_without_purchase: 7,
    first_order_time_online: {
      epoch_second: 1652897482,
      nano: 0,
    },
    last_order_time_online: {
      epoch_second: 1664963516,
      nano: 0,
    },
    first_order_time_offline: {
      epoch_second: 1652461199,
      nano: 0,
    },
    last_order_time_offline: {
      epoch_second: 1665198491,
      nano: 0,
    },
    store_id_of_first_order_offline: 349,
    store_id_of_last_order_offline: 394,
    store_of_first_order_offline: "cửa hàng lv 4 new",
    store_of_last_order_offline: "Cửa hàng của Mai",
    source_id_of_first_order_online: 129,
    source_id_of_last_order_online: 257,
    source_of_first_order_online: "Khác",
    source_of_last_order_online: "test chicken 14",
    source_ids: "1,110,111,129,187,221,222,223,225,226,228,229,230,231,232,147,237,257",
    channel_ids: "1,3,13,15",
    store_ids:
      "1,2,3,4,5,12,63,78,136,231,341,342,344,347,348,349,365,336,8,215,376,387,381,80,394",
    first_order_type: "online",
    last_order_type: "offline",
    first_order_place: null,
    last_order_place: null,
  },
  assigned_store_id: null,
  assigned_store: null,
  identity_number: null,
  utm: null,
  assigned_date: null,
  point: 1095955,
  region_code: "84",
  ecommerce_uid: null,
  customer_relationship: null,
  family_info: [],
};
const loyaltyPointDataTest: any = {
  id: 7380,
  customer_id: 3014155,
  loyalty_level_id: 22,
  loyalty_level: "SIÊU VIP",
  point: 1095955,
  total_order_count: 5037,
  total_money_spend: 3895619804,
  total_subtract_lock_point: null,
  level_change_time: "2022-09-07T17:00:00.000+00:00",
  money_maintain_current_level: 6246575.34,
  remain_amount_to_level_up: null,
  money_spend_in_year: 3890722002,
  created_date: "2022-05-18T18:11:23.000+00:00",
  created_by: "system",
  updated_date: "2022-10-08T03:08:12.000+00:00",
  updated_by: "system",
  card: null,
};
const loyaltyUsageRulesDataTest: any = [
  {
    id: 43,
    rank_id: 0,
    rank_name: "Default",
    limit_order_percent: 30,
    limit_line_percent: 30,
    block_order_have_discount: false,
  },
  {
    id: null,
    rank_id: 2,
    rank_name: "VIP G",
    limit_order_percent: null,
    limit_line_percent: null,
    block_order_have_discount: false,
  },
  {
    id: null,
    rank_id: 4,
    rank_name: "Vip R",
    limit_order_percent: null,
    limit_line_percent: null,
    block_order_have_discount: false,
  },
  {
    id: null,
    rank_id: 14,
    rank_name: "VIP S",
    limit_order_percent: null,
    limit_line_percent: null,
    block_order_have_discount: false,
  },
  {
    id: null,
    rank_id: 22,
    rank_name: "SIÊU VIP",
    limit_order_percent: null,
    limit_line_percent: null,
    block_order_have_discount: false,
  },
];

const setup = () => {
  render(
    <BrowserRouter>
      <UpdateCustomerCard
        OrderDetail={orderDetailDataTest}
        customerDetail={customerDetailDataTest}
        loyaltyPoint={loyaltyPointDataTest}
        loyaltyUsageRules={loyaltyUsageRulesDataTest}
      />
    </BrowserRouter>,
  );
};

describe("customer card", () => {
  setup();
  it("source", async () => {
    await waitFor(() => {
      const sourceElement = document.querySelector(
        "#order_customer_card > div.ant-card-head > div > div.ant-card-extra > div > span:nth-child(1) > span:nth-child(1)",
      );
      expect(sourceElement?.innerHTML).toEqual("Nguồn:");

      const channelElement = document.querySelector(
        "#order_customer_card > div.ant-card-head > div > div.ant-card-extra > div > span:nth-child(3) > span:nth-child(1)",
      );
      expect(channelElement?.innerHTML).toEqual("Kênh:");
    });
  });

  it("address", async () => {
    await waitFor(() => {
      if (orderDetailDataTest.shipping_address) {
        const addressElement = document.querySelector(
          "#order_customer_card > div.ant-card-body > div:nth-child(2) > div.ant-col.font-weight-500.customer-info-left.ant-col-xs-16",
        );

        console.log("element", addressElement?.outerHTML);
        // expect(addressElement).toBeTruthy();
      }
    });
  });
});
