import { BaseModel } from "../BaseModel";
import { OrderDiscountModel } from "./OrderDiscountModel";
import { OrderItemModel } from "./OrderItemModel";
import { OrderPaymentModel } from "./OrderPaymentModel";

export interface OrderModel extends BaseModel {
  seq?: number;
  reference_code?: string;
  company_id: number;
  store_id: number;
  store: string;
  status: string;
  price_type: string;
  tax_treatment: string;
  source_id: number;
  source: string;
  note: string;
  tags: string;
  payment_method_id?: number;
  payment_method?: string;
  expected_payment_method_id?: number;
  expected_delivery_provider_id?: number;
  expected_delivery_type?: string;
  customer_note: string;
  sale_note: string;
  account_code: string;
  account: string;
  assignee_code: string;
  assignee: string;
  channel_id: number;
  channel: string;
  customer_id: number;
  phone?: string;
  email?: string;
  billing_address_id?: number;
  shipping_address_id?: number;
  items: Array<OrderItemModel>;
  fulfillments: [];
  discounts: Array<OrderDiscountModel>;
  payments: Array<OrderPaymentModel>;
  total: number;
  total_line_amount_after_line_discount: number;
  order_discount_rate: number;
  order_discount_value: number;
  discount_reason: string;
  total_discount: number;
  total_tax: number;
  currency: string,
  total_amount_free_form: number;
  total_paid_amount: number;
}
