const AccountType = {
  GET_DETAIL_ACCOUNT_REQUEST: 'GET_DETAIL_ACCOUNT_REQUEST',
  GET_DETAIL_ACCOUNT_RESPONSE: 'GET_DETAIL_ACCOUNT_RESPONSE',
  SAVE_ACCOUNT_STORE: 'SAVE_ACCOUNT_STORE',
};

export default AccountType;