export const AccountType = {
  GET_DETAIL_ACCOUNT_REQUEST: 'GET_DETAIL_ACCOUNT_REQUEST',
  GET_DETAIL_ACCOUNT_RESPONSE: 'GET_DETAIL_ACCOUNT_RESPONSE',
  SEARCH_ACCOUNT_REQUEST: 'SEARCH_ACCOUNT_REQUEST',
  GET_LIST_ACCOUNT_REQUEST: 'GET_LIST_ACCOUNT_REQUEST',
  GET_LIST_DEPARTMENT_REQUEST: 'GET_LIST_DEPARTMENT_REQUEST',
  GET_LIST_POSITION_REQUEST: 'GET_LIST_POSITION_REQUEST',
};


export const AuthType = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
}
