export const AccountType = {
  GET_DETAIL_ACCOUNT_REQUEST: 'GET_DETAIL_ACCOUNT_REQUEST',
  GET_DETAIL_ACCOUNT_RESPONSE: 'GET_DETAIL_ACCOUNT_RESPONSE',
  SEARCH_ACCOUNT_REQUEST: 'SEARCH_ACCOUNT_REQUEST',
  GET_LIST_ACCOUNT_REQUEST: 'GET_LIST_ACCOUNT_REQUEST',
  GET_LIST_DEPARTMENT_REQUEST: 'GET_LIST_DEPARTMENT_REQUEST',
  GET_LIST_POSITION_REQUEST: 'GET_LIST_POSITION_REQUEST',
  GET_LIST_SHIPPER_REQUEST: 'GET_LIST_SHIPPER_REQUEST',
};


