export const AuthType = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
    UNAUTHORIZED_SUCCESS: 'UNAUTHORIZED_SUCCESS',
  }
  
  export const RoleType = {
    GET_LIST_ROLE_REQUEST:'GET_LIST_ROLE_REQUEST',
    SEARCH_LIST_ROLE_REQUEST:'SEARCH_LIST_ROLE_REQUEST',
    CREATE_ROLES : 'CREATE_ROLES',
    GET_ROLE_BY_ID : 'GET_ROLE_BY_ID',
    UPDATE_ROLE : 'UPDATE_ROLE',
  }

  export const PermissionType = {
    UPDATE_USER_PERMISSION: 'UPDATE_USER_PERMISSION',
    GET_PROFILE_PERMISSION: 'GET_PROFILE_PERMISSION',
    GET_PROFILE_PERMISSION_SUCCESS: 'GET_PROFILE_PERMISSION_SUCCESS',
  }
  

  export const ModuleType = {
    GET_MODULE :"GET_MODULE",
  }