export const BankType={
    GET_BANK:"GET_BANK",
    GET_BANK_ACCOUNT:"GET_BANK_ACCOUNT",
    GET_ID_BANK_ACCOUNT:"GET_ID_BANK_ACCOUNT",
    POST_BANK_ACCOUNT:"POST_BANK_ACCOUNT",
    PUT_BANK_ACCOUNT:"PUT_BANK_ACCOUNT",
    DELETE_BANK_ACCOUNT:"DELETE_BANK_ACCOUNT",
}