export const BootstrapType = {
  GET_BOOTSTRAP_REQUEST: "GET_BOOTSTRAP_REQUEST",
  GET_BOOTSTRAP_SUCESSS: "GET_BOOTSTRAP_SUCESSS",
};
export const ContentType = {
  GET_COUNTRY_REQUEST: "GET_COUNTRY_REQUEST",
  GET_REGION_REQUEST: "GET_REGION_REQUEST",
  GET_DISTRICT_REQUEST: "GET_DISTRICT_REQUEST",
  GET_WARD_REQUEST: "GET_WARD_REQUEST",
  GET_GROUP_REQUEST: "GET_GROUP_REQUEST",
  GET_DISTRICT_BY_CITY_REQUEST: "GET_DISTRICT_BY_CITY_REQUEST",
  GET_CITY_BY_COUNTRY_REQUEST: "GET_CITY_BY_COUNTRY_REQUEST",
};
