export const BootstrapType = {
  GET_BOOTSTRAP_REQUEST: 'GET_BOOTSTRAP_REQUEST',
  GET_BOOTSTRAP_SUCESSS: 'GET_BOOTSTRAP_SUCESSS',
}
export const ContentType = {
  GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
}