export const SupplierType = {
  SEARCH_SUPPLIER_REQUEST: "SEARCH_SUPPLIER_REQUEST",
  GET_ALL_SUPPLIER_REQUEST: "GET_ALL_SUPPLIER_REQUEST",
  CREATE_SUPPLIER_REQUEST: "CREATE_SUPPLIER_REQUEST",
  EDIT_SUPPLIER_REQUEST: "EDIT_SUPPLIER_REQUEST",
  DETAIL_SUPPLIER_REQUEST: "DETAIL_SUPPLIER_REQUEST",
  DELETE_SUPPLIER_REQUEST: "DELETE_SUPPLIER_REQUEST",
  CREATE_ADDRESS_SUPPLIER_REQUEST: 'CREATE_ADDRESS_SUPPLIER_REQUEST',
  UPDATE_ADDRESS_SUPPLIER_REQUEST: 'UPDATE_ADDRESS_SUPPLIER_REQUEST',
  DELETE_ADDRESS_SUPPLIER_REQUEST: 'DELETE_ADDRESS_SUPPLIER_REQUEST',
  CREATE_CONTACT_SUPPLIER_REQUEST: 'CREATE_CONTACT_SUPPLIER_REQUEST',
  UPDATE_CONTACT_SUPPLIER_REQUEST: 'UPDATE_CONTACT_SUPPLIER_REQUEST',
  DELETE_CONTACT_SUPPLIER_REQUEST: 'DELETE_CONTACT_SUPPLIER_REQUEST',
  CREATE_PAYMENT_SUPPLIER_REQUEST: 'CREATE_PAYMENT_SUPPLIER_REQUEST',
  UPDATE_PAYMENT_SUPPLIER_REQUEST: 'UPDATE_PAYMENT_SUPPLIER_REQUEST',
  DELETE_PAYMENT_SUPPLIER_REQUEST: 'DELETE_PAYMENT_SUPPLIER_REQUEST',
};

export const StoreType = {
  GET_LIST_STORE_REQUEST: "GET_LIST_STORE_REQUEST",
  GET_LIST_STORE_REQUEST_SIMPLE: "GET_LIST_STORE_REQUEST_SIMPLE",
  GET_SEARCH_STORE_REQUEST:"GET_SEARCH_STORE_REQUEST",
  STORE_GET_ALL: "STORE_GET_ALL",
  STORE_SEARCH: "STORE_SEARCH",
  STORE_CREATE: "STORE_CREATE",
  STORE_DELETE: "STORE_DELETE",
  STORE_DETAIL: "STORE_DETAIL",
  STORE_UPDATE: "STORE_UPDATE",
  STORE_RANK: "STORE_RANK",
  STORE_DETAIL_CUSTOM: "STORE_DETAIL_CUSTOM",
  STORE_VALIDATE: "STORE_VALIDATE",
  STORE_TYPE: "STORE_TYPE",
  STORE_SEARCH_IDS:"STORE_SEARCH_IDS"
};

export const ImportType = {
  UPLOAD_CORE_FILE: "UPLOAD_CORE_FILE"
}