export const SupplierType = {
  SEARCH_SUPPLIER_REQUEST: 'SEARCH_SUPPLIER_REQUEST',
  GET_ALL_SUPPLIER_REQUEST: 'GET_ALL_SUPPLIER_REQUEST',
  CREATE_SUPPLIER_REQUEST: 'CREATE_SUPPLIER_REQUEST',
  EDIT_SUPPLIER_REQUEST: 'EDIT_SUPPLIER_REQUEST',
  DETAIL_SUPPLIER_REQUEST: 'DETAIL_SUPPLIER_REQUEST',
  DELETE_SUPPLIER_REQUEST: 'DELETE_SUPPLIER_REQUEST',
}

export const StoreType = {
  GET_LIST_STORE_REQUEST: 'GET_LIST_STORE_REQUEST',
  VALIDATE_STORE: 'VALIDATE_STORE',
}