export const CustomerType = {
  KEY_SEARCH_CUSTOMER_CHANGE: "KEY_SEARCH_CUSTOMER_CHANGE",
  CUSTOMER_DETAIL:"CUSTOMER_DETAIL",
  CREATE_CUSTOMER:"CREATE_CUSTOMER",
  UPDATE_CUSTOMER:"UPDATE_CUSTOMER",
  CUSTOMER_GROUPS: "CUSTOMER_GROUPS",
  CUSTOMER_TYPES: "CUSTOMER_TYPES",
  CUSTOMER_LEVELS: "CUSTOMER_LEVELS",
  CUSTOMER_LIST: "CUSTOMER_LIST",
  UPDATE_BILLING_ADDR: 'UPDATE_BILLING_ADDR',
  CREATE_BILLING_ADDR: 'CREATE_BILLING_ADDR',
  UPDATE_SHIPPING_ADDR: 'UPDATE_SHIPPING_ADDR',
  CREATE_SHIPPING_ADDR: 'CREATE_SHIPPING_ADDR',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  CREATE_CONTACT: 'CREATE_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  DELETE_BILLING_ADDR: 'DELETE_BILLING_ADDR',
  DELETE_SHIPPING_ADDR: 'DELETE_SHIPPING_ADDR'
};
