export const CustomerType = {
  KEY_SEARCH_CUSTOMER_CHANGE: "KEY_SEARCH_CUSTOMER_CHANGE",
  CUSTOMER_DETAIL:"CUSTOMER_DETAIL",
  CREATE_CUSTOMER:"CREATE_CUSTOMER",
  UPDATE_CUSTOMER:"UPDATE_CUSTOMER",
  CUSTOMER_GROUPS: "CUSTOMER_GROUPS",
  CUSTOMER_TYPES: "CUSTOMER_TYPES",
  CUSTOMER_LEVELS: "CUSTOMER_LEVELS",
  CUSTOMER_LIST: "CUSTOMER_LIST"
};
