export const EcommerceType = {
    CREATE_ECOMMERCE_CONFIG_REQUEST: 'CREATE_ECOMMERCE_CONFIG_REQUEST',
    GET_ECOMMERCE_CONFIG_BY_ID_REQUEST: 'GET_ECOMMERCE_CONFIG_BY_ID_REQUEST',
    GET_ECOMMERCE_CONFIG_REQUEST: 'GET_ECOMMERCE_CONFIG_REQUEST',
    UPDATE_ECOMMERCE_CONFIG_REQUEST: 'UPDATE_ECOMMERCE_CONFIG_REQUEST',
    DELETE_ECOMMERCE_CONFIG_REQUEST: 'DELETE_ECOMMERCE_CONFIG_REQUEST',
  };
  
  
  