export const EcommerceType = {
    CREATE_ECOMMERCE_CONFIG_REQUEST: 'CREATE_ECOMMERCE_CONFIG_REQUEST',
    CONNECT_ECOMMERCE_CONFIG_REQUEST: 'CONNECT_ECOMMERCE_CONFIG_REQUEST',
    GET_ECOMMERCE_CONFIG_BY_ID_REQUEST: 'GET_ECOMMERCE_CONFIG_BY_ID_REQUEST',
    GET_ECOMMERCE_CONFIG_REQUEST: 'GET_ECOMMERCE_CONFIG_REQUEST',
    UPDATE_ECOMMERCE_CONFIG_REQUEST: 'UPDATE_ECOMMERCE_CONFIG_REQUEST',
    DELETE_ECOMMERCE_CONFIG_REQUEST: 'DELETE_ECOMMERCE_CONFIG_REQUEST',
    GET_ECOMMERCE_CONFIG_INFO_REQUEST: "GET_ECOMMERCE_CONFIG_INFO_REQUEST",
    GET_ECOMMERCE_VARIANTS_REQUEST: "GET_ECOMMERCE_VARIANTS_REQUEST",
    GET_ECOMMERCE_SHOP_REQUEST: "GET_ECOMMERCE_SHOP_REQUEST"
  };
  
  
  