export const GoodsReceiptsType = {
  GET_GOODS_RECEIPTS_TYPE:"GET_GOODS_RECEIPTS_TYPE",
  CREATE_GOODS_RECEIPTS:"CREATE_GOODS_RECEIPTS",
  UPDATE_GOODS_RECEIPTS:"UPDATE_GOODS_RECEIPTS",
  SEARCH_GOODS_RECEIPTS:"SEARCH_GOODS_RECEIPTS",
  DELETE_GOODS_RECEIPTS:"DELETE_GOODS_RECEIPTS",
  GETBYID_GOODS_RECEIPTS:"GETBYID_GOODS_RECEIPTS",
}