export const GoodsReceiptsType = {
  GET_GOODS_RECEIPTS_TYPE:"GET_GOODS_RECEIPTS_TYPE",
  CREATE_GOODS_RECEIPTS:"CREATE_GOODS_RECEIPTS",
  UPDATE_GOODS_RECEIPTS:"UPDATE_GOODS_RECEIPTS",
  SEARCH_GOODS_RECEIPTS:"SEARCH_GOODS_RECEIPTS",
  DELETE_GOODS_RECEIPTS:"DELETE_GOODS_RECEIPTS",
  GETBYID_GOODS_RECEIPTS:"GETBYID_GOODS_RECEIPTS",
  GET_ORDER_CONCERN_GOODS_RECEIPTS:"GET_ORDER_CONCERN_GOODS_RECEIPTS",
  GET_ORDER_GOODS_RECEIPTS_ADD:"GET_ORDER_GOODS_RECEIPTS_ADD",
  GET_PRINT_GOODS_RECEIPTS:"GET_PRINT_GOODS_RECEIPTS",
}