const InventoryType = {
  GET: "INVENTORY_GET_LIST",
  GET_DETAIL: "INVENTORY_GET_LIST_DETAIL",
  GET_HISTORY: "INVENTORY_GET_LIST_HISTORY",
  GET_DETAIL_lIST_VARIANT:"GET_DETAIL_lIST_VARIANT"
}

export {InventoryType};