const InventoryType = {
  GET: "INVENTORY_GET_LIST",
  GET_DETAIL: "INVENTORY_GET_LIST_DETAIL",
  GET_HISTORY: "INVENTORY_GET_LIST_HISTORY",
  GET_DETAIL_lIST_VARIANT: "GET_DETAIL_lIST_VARIANT",
  GET_STORE: "INVENTORY_GET_SENDER_STORE",
  GET_VARIANT_BY_STORE: 'INVENTORY_GET_VARIANT_BY_STORE',
  UPLOAD_FILES: 'INVENTORY_UPLOAD_FILES',
  CREATE_INVENTORY_TRANSFER: 'CREATE_INVENTORY_TRANSFER',
  UPDATE_INVENTORY_TRANSFER: 'UPDATE_INVENTORY_TRANSFER',
  GET_LIST_INVENTORY_TRANSFER: 'GET_LIST_INVENTORY_TRANSFER',
  GET_DETAIL_INVENTORY_TRANSFER: 'GET_DETAIL_INVENTORY_TRANSFER',
  DELETE_INVENTORY_TRANSFER: 'DELETE_INVENTORY_TRANSFER',
}

export {InventoryType};