export const MarketingType = {
  CAMPAIGN_LIST: "CAMPAIGN_LIST",
  CAMPAIGN_DETAIL: "CAMPAIGN_DETAIL",
  GET_CAMPAIGN_REF_ID: "GET_CAMPAIGN_REF_ID",
  CAMPAIGN_CONTACT_LIST: "CAMPAIGN_CONTACT_LIST",
  GET_BRAND_NAME: "GET_BRAND_NAME",
  GET_MESSAGE_TEMPLATE: "GET_MESSAGE_TEMPLATE",
  GET_IMPORT_FILE_TEMPLATE: "GET_IMPORT_FILE_TEMPLATE",
  CAMPAIGN_IMPORT_FILE: "CAMPAIGN_IMPORT_FILE",
  CAMPAIGN_CONTACT: "CAMPAIGN_CONTACT",
  CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
  UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
};
