export const OrderType = {
  GET_LIST_SOURCE_REQUEST: 'GET_LIST_SOURCE_REQUEST',
  GET_LIST_SOURCE_RESPONSE: 'GET_LIST_SOURCE_RESPONSE',
  GET_LIST_SOURCE_ERROR: 'GET_LIST_SOURCE_ERROR',
  ORDER_DISCOUNT_TEXT_CHANGE: 'ORDER_DISCOUNT_TEXT_CHANGE',
  CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
}