export const OrderType = {
  GET_LIST_SOURCE_REQUEST: "GET_LIST_SOURCE_REQUEST",
  GET_LIST_SOURCE_RESPONSE: "GET_LIST_SOURCE_RESPONSE",
  GET_LIST_SOURCE_ERROR: "GET_LIST_SOURCE_ERROR",
  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  GET_LIST_PAYMENT_METHOD: "GET_LIST_PAYMENT_METHOD",
  GET_ORDER_DETAIL_REQUEST: "GET_ORDER_DETAIL_REQUEST",
  UPDATE_FULFILLMENT_METHOD: "UPDATE_FULFILLMENT_METHOD",
  UPDATE_SHIPPING_METHOD: "UPDATE_SHIPPING_METHOD",
  UPDATE_PAYMENT_METHOD: "UPDATE_PAYMENT_METHOD",
  GET_LIST_DELIVERY_SERVICE: "GET_LIST_DELIVERY_SERVICE",
  GET_INFO_DELIVERY_GHTK: "GET_INFO_DELIVERY_GHTK",
};
