export const ORDER_RETURN_TYPES = {
  GET_LIST_RETURN_REASON: "GET_LIST_RETURN_REASON",
  SET_IS_RECEIVED_PRODUCT: "SET_IS_RECEIVED_PRODUCT",
  REFUND: "REFUND",
  CREATE_ORDER_EXCHANGE: "CREATE_ORDER_EXCHANGE",
  GET_ORDER_RETURN_LOGS: "GET_ORDER_RETURN_LOGS",
};
