const OtherType = {
  LOADING_FROM_LOCAL_STORAGE_REQUEST: "LOADING_FROM_LOCAL_STORAGE_REQUEST",
  LOADING_FROM_LOCAL_STORAGE_SUCCESS: "LOADING_FROM_LOCAL_STORAGE_SUCCESS",
  FETCH_API_ERROR: "FETCH_API_ERROR",
};

export default OtherType;
