const OtherType = {
  LOADING_FROM_LOCAL_STORAGE_REQUEST: 'LOADING_FROM_LOCAL_STORAGE_REQUEST',
  LOADING_FROM_LOCAL_STORAGE_SUCCESS: 'LOADING_FROM_LOCAL_STORAGE_SUCCESS',
};

export default OtherType;