export const CategoryType = {
  GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
}

export const MaterialType = {
  GET_MATERIAL_REQUEST: 'GET_MATERIAL_REQUEST',
  DELETE_ONE_MATERIAL_REQUEST: 'DELETE_MATERIAL_REQUEST',
  DELETE_MANY_MATERIAL_REQUEST: 'DELETE_MANY_MATERIAL_REQUEST',
  CREATE_MATERIAL_REQUEST: 'CREATE_MATERIAL_REQUEST',
}