export const CategoryType = {
  GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
}

export const MaterialType = {
  GET_MATERIAL_REQUEST: 'GET_MATERIAL_REQUEST',
  DELETE_ONE_MATERIAL_REQUEST: 'DELETE_MATERIAL_REQUEST',
  DELETE_MANY_MATERIAL_REQUEST: 'DELETE_MANY_MATERIAL_REQUEST',
  CREATE_MATERIAL_REQUEST: 'CREATE_MATERIAL_REQUEST',
  DETAIL_MATERIAL_REQUEST: 'DETAIL_MATERIAL_REQUEST',
  UPDATE_MATERIAL_REQUEST: 'UPDATE_MATERIAL_REQUEST',
}

export const ProductType = {
  SEARCH_PRODUCT_REQUEST: 'SEARCH_PRODUCT_REQUEST',
}