const DiscountType = {
  GET_LIST_DISCOUNTS: 'GET_LIST_DISCOUNTS',
  GET_PRICE_RULES: 'GET_PRICE_RULES',
  GET_LIST_DISCOUNT_CODE: 'GET_LIST_DISCOUNT_CODE',
  DELETE_PRICE_RULE_BY_ID: 'DELETE_PRICE_RULE_BY_ID',
  GET_PROMO_CODE_DETAIL: 'GET_PROMO_CODE_DETAIL',
  ADD_PRICE_RULE: 'ADD_PRICE_RULE'
}

const PromoCodeType = {
  GET_LIST_PROMO_CODE: 'GET_LIST_PROMO_CODE',
  GET_PROMO_CODE_BY_ID: 'GET_PROMO_CODE_BY_ID',
  DELETE_PROMO_CODE_BY_ID: 'DELETE_PROMO_CODE_BY_ID',
  UPDATE_PROMO_CODE_BY_ID: 'UPDATE_PROMO_CODE_BY_ID',
  ADD_PROMO_CODE_MANUAL: 'ADD_PROMO_CODE_MANUAL',
}

export { DiscountType, PromoCodeType }
