const DiscountType = {
  GET_LIST_DISCOUNTS: 'GET_LIST_DISCOUNTS',
  GET_PRICE_RULES: 'GET_PRICE_RULES',
  GET_LIST_DISCOUNT_CODE: 'GET_LIST_DISCOUNT_CODE',
  DELETE_PRICE_RULE_BY_ID: 'DELETE_PRICE_RULE_BY_ID',
}

export { DiscountType }
