const DiscountType = {
  GET_LIST_DISCOUNTS: "GET_LIST_DISCOUNTS",
  GET_PRICE_RULES: "GET_PRICE_RULES",
  GET_LIST_DISCOUNT_CODE: "GET_LIST_DISCOUNT_CODE",
  DELETE_PRICE_RULE_BY_ID: "DELETE_PRICE_RULE_BY_ID",
  GET_PROMO_CODE_DETAIL: "GET_PROMO_CODE_DETAIL",
  ADD_PRICE_RULE: "ADD_PRICE_RULE",
  GET_DISCOUNT_CODE_DETAIL: "GET_DISCOUNT_CODE_DETAIL",
  ENABLE_PRICE_RULE: "ENABLE_PRICE_RULE",
  DISABLE_PRICE_RULE: "DISABLE_PRICE_RULE",
  DELETE_BULK_PRICE_RULE: "DELETE_BULK_PRICE_RULE",
  GET_VARIANTS: "GET_VARIANTS",
  UPDATE_PRICE_RULE_BY_ID: "UPDATE_PRICE_RULE_BY_ID",
};

const PromoCodeType = {
  CHECK_PROMO_CODE: "CHECK_PROMO_CODE",
  GET_LIST_PROMO_CODE: "GET_LIST_PROMO_CODE",
  GET_PROMO_CODE_BY_ID: "GET_PROMO_CODE_BY_ID",
  DELETE_PROMO_CODE_BY_ID: "DELETE_PROMO_CODE_BY_ID",
  UPDATE_PROMO_CODE_BY_ID: "UPDATE_PROMO_CODE_BY_ID",
  ADD_PROMO_CODE: "ADD_PROMO_CODE",
  DELETE_PROMO_CODE_BULK: "DELETE_PROMO_CODE_BULK",
  GET_VARIANTS: "GET_VARIANTS",
  PUBLISHED_PROMO_CODE_BULK: "PUBLISHED_PROMO_CODE_BULK",
  ENABLE_PROMO_CODE_BULK: "ENABLE_PROMO_CODE_BULK",
  DISABLE_PROMO_CODE_BULK: "DISABLE_PROMO_CODE_BULK",
};

const PriceRuleType = {
  CREATE_PRICE_RULE: "CREATE_PRICE_RULE",
};
export {DiscountType, PromoCodeType, PriceRuleType};
