export const POType = {
  CREATE_PO_REQUEST: "CREATE_PO_REQUEST",
  UPDATE_PO_REQUEST: "UPDATE_PO_REQUEST",
  DETAIL_PO_REQUEST: "DETAIL_PO_REQUEST",
  SEARCH_PO_REQUEST: "SEARCH_PO_REQUEST",
  DELETE_PO_REQUEST: "DELETE_PO_REQUEST",
  RETURN_PO_REQUEST: "RETURN_PO_REQUEST",
  GET_PRINT_CONTENT: "GET_PRINT_CONTENT",
  CANCEL_PO_REQUEST: "CANCEL_PO_REQUEST",
  UPDATE_PO_FINANCIAL_STATUS_REQUEST: "UPDATE_PO_FINANCIAL_STATUS_REQUEST",
  EXPORT_PO: "EXPORT_PO",
};

export const PaymentConditionsType = {
  GET_PAYMENT_CONDITIONS_REQUEST: "GET_PAYMENT_CONDITIONS_REQUEST",
};
export const POPaymentType = {
  CREATE_PO_PAYMENT_REQUEST: "CREATE_PO_PAYMENT_REQUEST",
  UPDATE_PO_PAYMENT_REQUEST: "UPDATE_PO_PAYMENT_REQUEST",
  DELETE_PO_PAYMENT_REQUEST: "DELETE_PO_PAYMENT_REQUEST",
};

export const POProcumentType = {
  CREATE_PO_PROCUMENT_REQUEST: "CREATE_PO_PROCUMENT_REQUEST",
  UPDATE_PO_PROCUMENT_REQUEST: "UPDATE_PO_PROCUMENT_REQUEST",
  FINNISH_PO_PROCUMENT_REQUEST: "FINNISH_PO_PROCUMENT_REQUEST",
  DELETE_PO_PROCUMENT_REQUEST: "DELETE_PO_PROCUMENT_REQUEST",
  SEARCH_PROCUREMENT: "SEARCH_PROCUREMENT",
  IMPORT_PROCUMENT: "IMPORT_PROCUMENT",
};

export const POConfig = {
  CREATE_PO_CONFIG: "CREATE_PO_CONFIG",
  UPDATE_PO_CONFIG: "UPDATE_PO_CONFIG",
  GET_PO_CONFIG: "GET_PO_CONFIG", 
};