export const POType = {
  CREATE_PO_REQUEST: 'CREATE_PO_REQUEST',
  UPDATE_PO_REQUEST: 'UPDATE_PO_REQUEST',
  DETAIL_PO_REQUEST: 'DETAIL_PO_REQUEST',
    SEARCH_PO_REQUEST: 'SEARCH_PO_REQUEST',
  DELETE_PO_REQUEST: "DELETE_PO_REQUEST",
  UPDATE_PO_FINANCIAL_STATUS_REQUEST: 'UPDATE_PO_FINANCIAL_STATUS_REQUEST',
}

export const PaymentConditionsType = {
  GET_PAYMENT_CONDITIONS_REQUEST: "GET_PAYMENT_CONDITIONS_REQUEST",
};
export const POPaymentType = {
  CREATE_PO_PAYMENT_REQUEST: 'CREATE_PO_PAYMENT_REQUEST',
  UPDATE_PO_PAYMENT_REQUEST: 'UPDATE_PO_PAYMENT_REQUEST',
}

export const POProcumentType = {
  CREATE_PO_PROCUMENT_REQUEST: 'CREATE_PO_PROCUMENT_REQUEST',
  UPDATE_PO_PROCUMENT_REQUEST: 'UPDATE_PO_PROCUMENT_REQUEST',
  FINNISH_PO_PROCUMENT_REQUEST: 'FINNISH_PO_PROCUMENT_REQUEST',
}


