export const POType = {
  CREATE_PO_REQUEST: 'CREATE_PO_REQUEST',
  UPDATE_PO_REQUEST: 'UPDATE_PO_REQUEST',
  DETAIL_PO_REQUEST: 'DETAIL_PO_REQUEST',
  SEARCH_PO_REQUEST: 'SEARCH_PO_REQUEST',
}

export const PaymentConditionsType = {
  GET_PAYMENT_CONDITIONS_REQUEST: 'GET_PAYMENT_CONDITIONS_REQUEST',
}

