const SearchType = {
  KEY_SEARCH_CHANGE: "KEY_SEARCH_CHANGE",
  UPDATE_RESULT_SEARCH: "UPDATE_RESULT_SEARCH",
  CLEAR_RESULT: "CLEAR_RESULT",
  SEARCH_BAR_CODE: "SEARCH_BAR_CODE",
  SEARCH_GIFT: "SEARCH_GIFT",
};

export { SearchType };
