export const SETTING_TYPES = {
  orderProcessingStatus: {
    listData: "LIST_ALL_ORDER_PROCESSING_STATUS",
    create: "CREATE_ORDER_PROCESSING_STATUS",
    delete: "DELETE_ORDER_PROCESSING_STATUS",
    edit: "EDIT_ORDER_PROCESSING_STATUS",
  },
  orderSources: {
    listData: "LIST_DATA_ORDER_SOURCES",
    listSourceCompany: "LIST_SOURCE_COMPANY",
    create: "CREATE_ORDER_SOURCE",
    delete: "DELETE_ORDER_SOURCE",
    edit: "EDIT_ORDER_SOURCE",
  },
  orderSettings: {
    GET_ORDER_CONFIG_PRINT: "GET_ORDER_CONFIG_PRINT",
    GET_ORDER_CONFIG_ACTION: "GET_ORDER_CONFIG_ACTION",
    GET_ORDER_CONFIGURATIONS: "GET_ORDER_CONFIGURATIONS",
    EDIT_ORDER_CONFIGURATIONS: "EDIT_ORDER_CONFIGURATIONS",
    GET_IS_ALLOW_TO_SELL_WHEN_NOT_AVAILABLE_STOCK:
      "GET_IS_ALLOW_TO_SELL_WHEN_NOT_AVAILABLE_STOCK",
    CONFIGURE_IS_ALLOW_TO_SELL_WHEN_NOT_AVAILABLE_STOCK:
      "CONFIGURE_IS_ALLOW_TO_SELL_WHEN_NOT_AVAILABLE_STOCK",
    LIST_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE:
      "LIST_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE",
    CREATE_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE:
      "CREATE_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE",
    GET_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE_DETAIL:
      "GET_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE_DETAIL",
    UPDATE_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE:
      "UPDATE_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE",
    DELETE_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE:
      "DELETE_CONFIGURATION_SHIPPING_SERVICE_AND_SHIPPING_FEE",
  },
	smsSettingsType: {
		GET_SMS_CONFIG: 'GET_SMS_CONFIG',
		UPDATE_SMS_CONFIG: 'UPDATE_SMS_CONFIG',
		CONFIG_SMS_MESSAGE: 'CONFIG_SMS_MESSAGE',
	}
};
