const StoreType = {
  GET_LIST_STORE_REQUEST: 'GET_LIST_STORE_REQUEST',
  GET_LIST_STORE_RESPONSE: 'GET_LIST_STORE_RESPONSE',
  GET_LIST_STORE_ERROR: 'GET_LIST_STORE_ERROR',
  VALIDATE_STORE: 'VALIDATE_STORE',
  SET_STORE_DEFAULT: 'SET_STORE_DEFAULT',
  SAVE_ACCOUNT_STORE: 'SAVE_ACCOUNT_STORE',

};

export default StoreType;