export const WarrantyType = {
  GET_DATA_WARRANTIES_REQUEST: 'GET_DATA_WARRANTIES_REQUEST',
  GET_DETAILS_WARRANTY_REQUEST: 'GET_DETAILS_WARRANTY_REQUEST',
  CREATE_WARRANTY_REQUEST: 'CREATE_WARRANTY_REQUEST',
  UPDATE_WARRANTY_REQUEST: 'UPDATE_WARRANTY_REQUEST',
  GET_WARRANTY_REASONS_REQUEST: 'GET_WARRANTY_REASONS_REQUEST',
};
