import { render, waitFor } from "@testing-library/react";
import { Provider } from "react-redux";
import { handleFixWindowMatchMediaTest, store } from "screens/order-online/utils/test.utils";
import OrderFulfillmentDetail from ".";

const orderDetailDataTest: any = {
  id: 21903525,
  code: "SO021903525",
  version: 1,
  created_by: "YD10893",
  created_name: "LÊ VĂN LONG",
  created_date: "2022-10-05T08:48:19Z",
  updated_by: "YD10893",
  updated_name: "LÊ VĂN LONG",
  updated_date: "2022-10-08T02:58:07Z",
  reference_code: "",
  company_id: 1,
  company: "Công ty cổ phần thời trang YODY",
  store_id: 2,
  store_code: "YDVNHTH01",
  store: "YODY Đức Thọ",
  store_phone_number: "18002086",
  store_full_address: "58 Trần Phú-phường Bắc Hồng- thị xã Hồng Lĩnh- tỉnh Hà Tĩnh",
  status: "finished",
  price_type: "retail_price",
  tax_treatment: "inclusive",
  source_id: 256,
  source_code: "SC000323",
  source: "Đơn test 14",
  note: "(N.a)",
  tags: "",
  payment_method_id: null,
  payment_method_code: null,
  payment_method: null,
  expected_payment_method_id: null,
  expected_delivery_provider_id: null,
  expected_delivery_type: null,
  customer_note: "",
  sale_note: null,
  account_code: "YD10893",
  account: "LÊ VĂN LONG",
  marketer_code: null,
  marketer: null,
  coordinator_code: "YD99999",
  coordinator: "Quản trị viên",
  assignee_code: "YD10893",
  assignee: "LÊ VĂN LONG",
  channel_id: 13,
  channel_code: "ADMIN",
  channel: "Admin",
  customer_id: 7422471,
  customer: "LÊ VĂN LƯƠN",
  customer_phone_number: "0987363524",
  customer_email: "",
  fulfillment_status: "shipped",
  packed_status: null,
  received_status: null,
  payment_status: "paid",
  return_status: "returned",
  total_line_amount_after_line_discount: 229000,
  total: 231200,
  order_discount_rate: null,
  order_discount_value: null,
  discount_reason: null,
  total_discount: 20000,
  total_tax: null,
  finalized_account_code: "YD10893",
  cancel_account_code: null,
  finish_account_code: null,
  finalized_on: "2022-10-05T08:48:20.000+00:00",
  cancelled_on: null,
  finished_on: "2022-10-08T02:57:36.000+00:00",
  items: [
    {
      id: 228658,
      code: "7b6a1315-c6ab-4410-ae68-9abefdde55e1",
      version: 1,
      created_by: "YD10893",
      created_name: "LÊ VĂN LONG",
      created_date: "2022-10-05T08:48:20Z",
      updated_by: "YD10893",
      updated_name: "LÊ VĂN LONG",
      updated_date: "2022-10-05T08:48:20Z",
      order_line_item_id: null,
      sku: "APK5169-VAG-2",
      variant_id: 27816,
      variant: "Polo nam kid phối bo - Vàng - 2",
      product_id: 4637,
      product: "Polo nam kid phối bo",
      product_code: "APK5169",
      variant_barcode: "2000190943161",
      product_type: "normal",
      quantity: 1,
      price: 229000,
      amount: 229000,
      discount_items: [],
      note: "",
      variant_image: "",
      unit: "piece",
      warranty: "",
      tax_rate: 0,
      tax_include: null,
      is_composite: null,
      line_amount_after_line_discount: 229000,
      discount_rate: 0,
      discount_value: 0,
      discount_amount: 0,
      position: 1,
      weight: 150,
      weight_unit: "g",
      type: "normal",
    },
  ],
  discounts: [
    {
      id: 83725,
      code: "4d21af74-2197-4d61-8af6-441c77eeb3f8",
      version: 1,
      created_by: "YD10893",
      created_name: "LÊ VĂN LONG",
      created_date: "2022-10-05T09:11:05Z",
      updated_by: "YD10893",
      updated_name: "LÊ VĂN LONG",
      updated_date: "2022-10-05T09:11:05Z",
      rate: 8.73,
      value: 20000,
      amount: 20000,
      promotion_id: 1512,
      discount_code: null,
      source: "",
      reason: "N.a",
      order_id: 21903525,
    },
  ],
  pre_payments: null,
  payments: [
    {
      id: 125295,
      code: "a11b243a-df32-442d-8f2f-3f3b39a01ee3",
      version: 1,
      created_by: "YD10893",
      created_name: "LÊ VĂN LONG",
      created_date: "2022-10-08T02:57:36Z",
      updated_by: "YD10893",
      updated_name: "LÊ VĂN LONG",
      updated_date: "2022-10-08T02:57:36Z",
      fulfillment_id: null,
      payment_method_id: 0,
      payment_method_code: "cod",
      payment_method: "COD",
      amount: 231200,
      reference: null,
      source: "cod",
      paid_amount: 231200,
      return_amount: 0,
      status: "paid",
      customer_id: null,
      type: "cod",
      invoice_id: null,
      note: null,
      point: null,
      bank_account_id: null,
      bank_account_number: null,
      bank_account_holder: null,
      bank_code: null,
      bank_name: null,
      ref_transaction_code: null,
      pay_url: null,
      short_link: null,
      expired_at: null,
    },
  ],
  fulfillments: [
    {
      id: 149101,
      code: "FM000149101",
      version: 1,
      created_by: "YD10893",
      created_name: "LÊ VĂN LONG",
      created_date: "2022-10-05T08:48:20Z",
      updated_by: "YD10893",
      updated_name: "LÊ VĂN LONG",
      updated_date: "2022-10-08T02:57:36Z",
      order_id: 21903525,
      account_code: "YD10893",
      assignee_code: "YD10893",
      delivery_type: "",
      status: "shipped",
      partner_status: null,
      shipment: {
        id: 73720,
        code: "b6234c94-2926-4ec9-8517-adaa65bf4b96",
        version: 1,
        created_by: "YD10893",
        created_name: "LÊ VĂN LONG",
        created_date: "2022-10-08T02:57:28Z",
        updated_by: "YD10893",
        updated_name: "LÊ VĂN LONG",
        updated_date: "2022-10-08T02:57:28Z",
        delivery_service_provider_id: null,
        delivery_service_provider_code: null,
        delivery_service_provider_name: null,
        delivery_service_provider_type: "pick_at_store",
        delivery_transport_type: null,
        delivery_service_note: null,
        handover_id: null,
        service: null,
        who_paid: null,
        fee_type: null,
        fee_base_on: null,
        delivery_fee: null,
        reference_status: null,
        reference_status_explanation: null,
        cancel_reason: null,
        tracking_code: null,
        tracking_url: null,
        received_date: null,
        expected_received_date: null,
        shipping_fee_paid_to_three_pls: null,
        sender_address_id: null,
        sender_address: null,
        requirements: "open_try",
        requirements_name: null,
        note_to_shipper: null,
        fulfillment_id: 149101,
        cod: 231200,
        shipper_code: null,
        shipper_name: null,
        pushing_note: null,
        pushing_status: null,
        shipping_address: null,
        office_time: null,
        shipper_phone: null,
        recipient_sort_code: null,
        info_shipper: null,
        type_shipment: null,
      },
      billing_address_id: null,
      items: [
        {
          id: 185129,
          code: "33af543f-a258-4086-b8b7-1d15d15b108e",
          version: 1,
          created_by: "YD10893",
          created_name: "LÊ VĂN LONG",
          created_date: "2022-10-05T08:48:20Z",
          updated_by: "YD10893",
          updated_name: "LÊ VĂN LONG",
          updated_date: "2022-10-05T08:52:00Z",
          order_line_item_id: 228658,
          product_id: 4637,
          product: "Polo nam kid phối bo",
          product_code: "APK5169",
          variant_id: 27816,
          variant: "Polo nam kid phối bo - Vàng - 2",
          order_line_item_note: null,
          quantity: 1,
          base_price: null,
          discount_rate: 0,
          discount_value: 0,
          tax_type_id: null,
          tax_rate: 0,
          line_amount: null,
          line_discount_amount: null,
          line_amount_after_line_discount: 229000,
          weight: 150,
          weight_unit: "g",
          sku: "APK5169-VAG-2",
          variant_barcode: "2000190943161",
          unit: "piece",
        },
      ],
      stock_location_id: 2,
      returned_store_id: 2,
      payment_status: "",
      total: 251200,
      total_tax: null,
      total_discount: 0,
      total_quantity: 1,
      stock_out_account_code: null,
      receive_account_code: null,
      cancel_account_code: null,
      receive_cancellation_account_code: null,
      payments: null,
      picked_on: "2022-10-08T02:57:29.000+00:00",
      packed_on: "2022-10-08T02:57:29.000+00:00",
      shipped_on: "2022-10-08T02:57:36.000+00:00",
      export_on: "2022-10-08T02:57:36.000+00:00",
      received_on: null,
      cancel_date: null,
      return_status: "unreturned",
      receive_cancellation_on: null,
      status_before_cancellation: null,
      discount_rate: 8.73,
      discount_value: 20000,
      discount_amount: null,
      total_line_amount_after_line_discount: 229000,
      returning_on: null,
      sub_reason_detail_id: null,
      reason_name: null,
      sub_reason_id: null,
      reason_id: null,
      sub_reason_name: null,
      sub_reason_detail_name: null,
    },
  ],
  currency: "VND",
  billing_address: {
    id: 29229,
    code: "8d65305c-18dc-4401-bd38-b2bbf1459b48",
    version: 10,
    created_by: "YD10893",
    created_name: "LÊ VĂN LONG",
    created_date: "2022-10-05T08:48:20Z",
    updated_by: "YD10893",
    updated_name: "LÊ VĂN LONG",
    updated_date: "2022-10-08T02:58:07Z",
    name: "LÊ VĂN LƯƠN",
    email: "lvlong96k@gmail.com",
    phone: null,
    country: null,
    city: null,
    district: null,
    ward: null,
    zip_code: null,
    full_address: "tân lập -yên my",
    buyer: "yody",
    tax_code: "343543534",
    note: null,
    order_id: 21903525,
    contract: false,
  },
  shipping_address: {
    id: 85862,
    code: "8fab6b5c-b807-4d0d-9b98-800a389661a2",
    version: 13,
    created_by: "YD10893",
    created_name: "LÊ VĂN LONG",
    created_date: "2022-10-05T08:48:20Z",
    updated_by: "YD10893",
    updated_name: "LÊ VĂN LONG",
    updated_date: "2022-10-08T02:58:07Z",
    name: "LÊ VĂN LƯƠN",
    email: null,
    phone: "0987363524",
    second_phone: "",
    country: null,
    city_id: 1,
    city: "TP. Hà Nội",
    district_id: 3,
    district: "Quận Hoàng Mai",
    ward_id: 22,
    ward: "Phường Giáp Bát",
    zip_code: null,
    full_address: "liêu hạ",
    channel: null,
  },
  shipping_fee_informed_to_customer: 22200,
  url: "",
  sub_status_id: 8,
  sub_status_code: "shipped",
  sub_status: "Thành công",
  order_returns: [
    {
      id: 12508,
      code: "SRN000012508",
      version: 1,
      created_by: "YD10893",
      created_name: "LÊ VĂN LONG",
      created_date: "2022-10-08T02:58:07Z",
      updated_by: "YD10893",
      updated_name: "LÊ VĂN LONG",
      updated_date: "2022-10-08T02:58:07Z",
      order_id: 21903525,
      order_code: "SO021903525",
      order_exchange_id: null,
      reference_code: "",
      company_id: 1,
      company: "Công ty cổ phần thời trang YODY",
      store_id: 110,
      store: "YODY Phố Nối",
      store_phone_number: "0911168258",
      store_full_address: "Đường 196- Ngã Tư Chợ Bao Bì , Thị trấn Bần Yên Nhân",
      returned_store_id: 110,
      status: "finished",
      price_type: "retail_price",
      tax_treatment: "inclusive",
      source_id: 256,
      source: "Đơn test 14",
      note: "",
      tags: "",
      customer_id: 7422471,
      customer: "LÊ VĂN LƯƠN",
      customer_email: "",
      customer_phone_number: "0987363524",
      payment_method_id: null,
      payment_method: null,
      expected_payment_method_id: null,
      expected_delivery_provider_id: null,
      expected_delivery_type: null,
      customer_note: "",
      sale_note: null,
      account_code: "YD10893",
      account: "LÊ VĂN LONG",
      assignee_code: "YD10893",
      assignee: "LÊ VĂN LONG",
      channel_id: 1,
      channel: "POS",
      payment_status: "paid",
      total_line_amount_after_line_discount: 229000,
      total: 209000,
      total_quantities: 1,
      currency: "VND",
      order_discount_rate: null,
      order_discount_value: null,
      discount_reason: null,
      total_discount: 20000,
      total_tax: null,
      finalized_account_code: "YD10893",
      cancel_account_code: null,
      finish_account_code: null,
      finalized_on: "2022-10-05T08:48:20.000+00:00",
      cancelled_on: null,
      finished_on: "2022-10-08T02:57:36.000+00:00",
      referent: null,
      url: "",
      total_amount: null,
      return_date: "2022-10-08T02:58:07.000+00:00",
      receive_date: "2022-10-08T02:58:07.000+00:00",
      point_refund: 0,
      money_refund: 209000,
      marketer_code: null,
      marketer: null,
      other_reason: null,
      reason: {
        id: 7,
        code: "order_return",
        name: "Đổi trả hàng",
      },
      sub_reason: {
        id: 58,
        code: "error_product",
        name: "Sản phẩm lỗi",
      },
      billing_address: {
        id: 29229,
        code: "8d65305c-18dc-4401-bd38-b2bbf1459b48",
        version: 10,
        created_by: "YD10893",
        created_name: "LÊ VĂN LONG",
        created_date: "2022-10-05T08:48:20Z",
        updated_by: "YD10893",
        updated_name: "LÊ VĂN LONG",
        updated_date: "2022-10-08T02:58:07Z",
        name: "LÊ VĂN LƯƠN",
        email: "lvlong96k@gmail.com",
        phone: null,
        country: null,
        city: null,
        district: null,
        ward: null,
        zip_code: null,
        full_address: "tân lập -yên my",
        buyer: "yody",
        tax_code: "343543534",
        note: null,
        order_id: 21903525,
        contract: false,
      },
      shipping_address: {
        id: 85862,
        code: "8fab6b5c-b807-4d0d-9b98-800a389661a2",
        version: 13,
        created_by: "YD10893",
        created_name: "LÊ VĂN LONG",
        created_date: "2022-10-05T08:48:20Z",
        updated_by: "YD10893",
        updated_name: "LÊ VĂN LONG",
        updated_date: "2022-10-08T02:58:07Z",
        name: "LÊ VĂN LƯƠN",
        email: null,
        phone: "0987363524",
        second_phone: "",
        country: null,
        city_id: 1,
        city: "TP. Hà Nội",
        district_id: 3,
        district: "Quận Hoàng Mai",
        ward_id: 22,
        ward: "Phường Giáp Bát",
        zip_code: null,
        full_address: "liêu hạ",
        channel: null,
      },
      items: [
        {
          id: 229005,
          code: "ceafa97a-6ffb-48cf-8559-b7d0b7c9d5d5",
          version: 1,
          created_by: "YD10893",
          created_name: "LÊ VĂN LONG",
          created_date: "2022-10-08T02:58:07Z",
          updated_by: "YD10893",
          updated_name: "LÊ VĂN LONG",
          updated_date: "2022-10-08T02:58:07Z",
          order_line_item_id: 228658,
          sku: "APK5169-VAG-2",
          variant_id: 27816,
          variant: "Polo nam kid phối bo - Vàng - 2",
          product_id: 4637,
          product: "Polo nam kid phối bo",
          product_code: "APK5169",
          variant_barcode: "2000190943161",
          product_type: "normal",
          quantity: 1,
          price: 229000,
          amount: 229000,
          discount_items: [],
          note: "",
          variant_image: "",
          unit: "piece",
          warranty: "",
          tax_rate: 0,
          tax_include: null,
          is_composite: null,
          line_amount_after_line_discount: 229000,
          discount_rate: 0,
          discount_value: 0,
          discount_amount: 0,
          position: 1,
          weight: 150,
          weight_unit: "g",
          type: "normal",
        },
      ],
      payments: [
        {
          id: 125296,
          code: "0fc23608-70f2-43e7-98ca-e59ab2b84ffc",
          version: 1,
          created_by: "YD10893",
          created_name: "LÊ VĂN LONG",
          created_date: "2022-10-08T02:58:07Z",
          updated_by: "YD10893",
          updated_name: "LÊ VĂN LONG",
          updated_date: "2022-10-08T02:58:07Z",
          fulfillment_id: null,
          payment_method_id: 2,
          payment_method_code: "cash",
          payment_method: "Tiền mặt",
          amount: 209000,
          reference: "",
          source: "",
          paid_amount: 209000,
          return_amount: 0,
          status: "paid",
          customer_id: null,
          type: "",
          invoice_id: null,
          note: null,
          point: null,
          bank_account_id: null,
          bank_account_number: null,
          bank_account_holder: null,
          bank_code: null,
          bank_name: null,
          ref_transaction_code: null,
          pay_url: null,
          short_link: null,
          expired_at: null,
        },
      ],
      discounts: [
        {
          id: 83817,
          code: "e29a7414-610f-404d-8a61-4974c1bb6e9a",
          version: 1,
          created_by: "YD10893",
          created_name: "LÊ VĂN LONG",
          created_date: "2022-10-08T02:58:07Z",
          updated_by: "YD10893",
          updated_name: "LÊ VĂN LONG",
          updated_date: "2022-10-08T02:58:07Z",
          rate: 8.73,
          value: 20000,
          amount: 20000,
          promotion_id: null,
          discount_code: null,
          source: null,
          reason: null,
          order_id: -1,
        },
      ],
      received: true,
      reason_name: "Đổi trả hàng",
      sub_reason_id: 58,
      reason_id: 7,
      sub_reason_name: "Sản phẩm lỗi",
      money_amount: 209000,
    },
  ],
  accumulate_point: null,
  linked_order_code: null,
  ecommerce_shop_id: null,
  ecommerce_shop_name: null,
  order_migration_id: null,
  created_on: "2022-10-05T08:48:19.000+00:00",
  campaign_id: null,
  utm_tracking: null,
  export_bill: true,
  migration_note: null,
  atomic_migration: false,
  actual_quantity: 1,
  uniform: false,
  automatic_discount: false,
  reason_name: null,
  sub_reason_id: null,
  reason_id: null,
  sub_reason_name: null,
};

const fulfillmentDataTest: any = {
  id: 149101,
  code: "FM000149101",
  version: 1,
  created_by: "YD10893",
  created_name: "LÊ VĂN LONG",
  created_date: "2022-10-05T08:48:20Z",
  updated_by: "YD10893",
  updated_name: "LÊ VĂN LONG",
  updated_date: "2022-10-08T02:57:36Z",
  order_id: 21903525,
  account_code: "YD10893",
  assignee_code: "YD10893",
  delivery_type: "",
  status: "shipped",
  partner_status: null,
  shipment: {
    id: 73720,
    code: "b6234c94-2926-4ec9-8517-adaa65bf4b96",
    version: 1,
    created_by: "YD10893",
    created_name: "LÊ VĂN LONG",
    created_date: "2022-10-08T02:57:28Z",
    updated_by: "YD10893",
    updated_name: "LÊ VĂN LONG",
    updated_date: "2022-10-08T02:57:28Z",
    delivery_service_provider_id: null,
    delivery_service_provider_code: null,
    delivery_service_provider_name: null,
    delivery_service_provider_type: "pick_at_store",
    delivery_transport_type: null,
    delivery_service_note: null,
    handover_id: null,
    service: null,
    who_paid: null,
    fee_type: null,
    fee_base_on: null,
    delivery_fee: null,
    reference_status: null,
    reference_status_explanation: null,
    cancel_reason: null,
    tracking_code: null,
    tracking_url: null,
    received_date: null,
    expected_received_date: null,
    shipping_fee_paid_to_three_pls: null,
    sender_address_id: null,
    sender_address: null,
    requirements: "open_try",
    requirements_name: null,
    note_to_shipper: null,
    fulfillment_id: 149101,
    cod: 231200,
    shipper_code: null,
    shipper_name: null,
    pushing_note: null,
    pushing_status: null,
    shipping_address: null,
    office_time: null,
    shipper_phone: null,
    recipient_sort_code: null,
    info_shipper: null,
    type_shipment: null,
  },
  billing_address_id: null,
  items: [
    {
      id: 185129,
      code: "33af543f-a258-4086-b8b7-1d15d15b108e",
      version: 1,
      created_by: "YD10893",
      created_name: "LÊ VĂN LONG",
      created_date: "2022-10-05T08:48:20Z",
      updated_by: "YD10893",
      updated_name: "LÊ VĂN LONG",
      updated_date: "2022-10-05T08:52:00Z",
      order_line_item_id: 228658,
      product_id: 4637,
      product: "Polo nam kid phối bo",
      product_code: "APK5169",
      variant_id: 27816,
      variant: "Polo nam kid phối bo - Vàng - 2",
      order_line_item_note: null,
      quantity: 1,
      base_price: null,
      discount_rate: 0,
      discount_value: 0,
      tax_type_id: null,
      tax_rate: 0,
      line_amount: null,
      line_discount_amount: null,
      line_amount_after_line_discount: 229000,
      weight: 150,
      weight_unit: "g",
      sku: "APK5169-VAG-2",
      variant_barcode: "2000190943161",
      unit: "piece",
    },
  ],
  stock_location_id: 2,
  returned_store_id: 2,
  payment_status: "",
  total: 251200,
  total_tax: null,
  total_discount: 0,
  total_quantity: 1,
  stock_out_account_code: null,
  receive_account_code: null,
  cancel_account_code: null,
  receive_cancellation_account_code: null,
  payments: null,
  picked_on: "2022-10-08T02:57:29.000+00:00",
  packed_on: "2022-10-08T02:57:29.000+00:00",
  shipped_on: "2022-10-08T02:57:36.000+00:00",
  export_on: "2022-10-08T02:57:36.000+00:00",
  received_on: null,
  cancel_date: null,
  return_status: "unreturned",
  receive_cancellation_on: null,
  status_before_cancellation: null,
  discount_rate: 8.73,
  discount_value: 20000,
  discount_amount: null,
  total_line_amount_after_line_discount: 229000,
  returning_on: null,
  sub_reason_detail_id: null,
  reason_name: null,
  sub_reason_id: null,
  reason_id: null,
  sub_reason_name: null,
  sub_reason_detail_name: null,
  tracking_log: [],
};

const deliveryServicesDataTest: any = [
  {
    id: 1,
    code: "yody",
    external_service_code: "yody",
    logo: "",
    name: "Yody Express",
    active: true,
    transport_types: [],
  },
  {
    id: 2,
    code: "ghtk",
    external_service_code: "ghtk",
    logo: "https://yody-file.s3.ap-southeast-1.amazonaws.com/%22delivery%22/2021-07-28-03-02-12_8d45e336-6f25-4cec-9fe6-a52162839f35.svg",
    name: "Giao hàng tiết kiệm",
    active: true,
    transport_types: [
      {
        id: 31,
        code: "fly",
        external_service_code: "ghtk",
        name: "Đường bay",
        description: null,
        active: false,
      },
      {
        id: 32,
        code: "road",
        external_service_code: "ghtk",
        name: "Đường bộ",
        description: null,
        active: true,
      },
    ],
  },
  {
    id: 3,
    code: "ghn",
    external_service_code: "ghn",
    logo: "https://yody-file.s3.ap-southeast-1.amazonaws.com/variant/2021-09-21-22-29-31_47725ba4-779a-426a-9eb9-67b79d8936fe.png",
    name: "Giao hàng nhanh",
    active: true,
    transport_types: [
      {
        id: 29,
        code: "1",
        external_service_code: "ghn",
        name: "Bay",
        description: "Bay",
        active: false,
      },
      {
        id: 30,
        code: "2",
        external_service_code: "ghn",
        name: "Đi bộ",
        description: "Đi bộ",
        active: true,
      },
    ],
  },
  {
    id: 4,
    code: "vtp",
    external_service_code: "vtp",
    logo: "https://yody-file.s3.ap-southeast-1.amazonaws.com/%22delivery%22/2021-07-28-03-02-12_7f5b5e68-b208-43b8-bd42-4927ffd45dd4.svg",
    name: "Viettel Post",
    active: true,
    transport_types: [
      {
        id: 33,
        code: "vcbo",
        external_service_code: "vtp",
        name: "Chuyển phát đường bộ",
        description: null,
        active: true,
      },
      {
        id: 34,
        code: "vcba",
        external_service_code: "vtp",
        name: "Chuyển phát đường bay",
        description: null,
        active: true,
      },
      {
        id: 35,
        code: "v02",
        external_service_code: "vtp",
        name: "TMDT Phát nhanh 2h",
        description: null,
        active: true,
      },
      {
        id: 36,
        code: "pttt",
        external_service_code: "vtp",
        name: "Phân tích thị trường",
        description: null,
        active: true,
      },
      {
        id: 37,
        code: "ncod",
        external_service_code: "vtp",
        name: "TMDT Bay",
        description: null,
        active: true,
      },
      {
        id: 38,
        code: "scod",
        external_service_code: "vtp",
        name: "SCOD Giao hàng thu tiền",
        description: null,
        active: true,
      },
      {
        id: 39,
        code: "ptn",
        external_service_code: "vtp",
        name: "TMDT Phát trong ngày",
        description: null,
        active: true,
      },
      {
        id: 40,
        code: "v30",
        external_service_code: "vtp",
        name: "V30",
        description: null,
        active: true,
      },
      {
        id: 41,
        code: "v20",
        external_service_code: "vtp",
        name: "V20",
        description: null,
        active: true,
      },
      {
        id: 42,
        code: "v25",
        external_service_code: "vtp",
        name: "V25",
        description: null,
        active: true,
      },
      {
        id: 43,
        code: "phs",
        external_service_code: "vtp",
        name: "TMDT Phát hôm sau",
        description: null,
        active: true,
      },
      {
        id: 44,
        code: "v35",
        external_service_code: "vtp",
        name: "V35",
        description: null,
        active: true,
      },
      {
        id: 45,
        code: "vcn",
        external_service_code: "vtp",
        name: "VCN Chuyển phát nhanh",
        description: null,
        active: true,
      },
      {
        id: 46,
        code: "v24",
        external_service_code: "vtp",
        name: "Đồng giá 24K",
        description: null,
        active: true,
      },
      {
        id: 47,
        code: "vtk",
        external_service_code: "vtp",
        name: "VTK Tiết kiệm",
        description: null,
        active: true,
      },
      {
        id: 48,
        code: "v60",
        external_service_code: "vtp",
        name: "V60 Dịch vụ Nhanh 60h",
        description: null,
        active: true,
      },
      {
        id: 49,
        code: "vht",
        external_service_code: "vtp",
        name: "VHT Phát Hỏa tốc",
        description: null,
        active: true,
      },
      {
        id: 50,
        code: "vbs",
        external_service_code: "vtp",
        name: "VBS Nhanh theo hộp",
        description: null,
        active: true,
      },
      {
        id: 51,
        code: "vbe",
        external_service_code: "vtp",
        name: "VBE Tiết kiệm theo hộp",
        description: null,
        active: true,
      },
      {
        id: 52,
        code: "ecod",
        external_service_code: "vtp",
        name: "ECOD Giao hành thu tiền tiết kiệm",
        description: null,
        active: true,
      },
      {
        id: 53,
        code: "lcod",
        external_service_code: "vtp",
        name: "TMDT Bộ",
        description: null,
        active: true,
      },
      {
        id: 54,
        code: "v510",
        external_service_code: "vtp",
        name: "Dịch vụ 5+ gói 1000g",
        description: null,
        active: true,
      },
      {
        id: 55,
        code: "v520",
        external_service_code: "vtp",
        name: "Dịch vụ 5+ gói 2000g",
        description: null,
        active: true,
      },
      {
        id: 56,
        code: "lstd",
        external_service_code: "vtp",
        name: "Hàng nặng nhanh",
        description: null,
        active: true,
      },
      {
        id: 57,
        code: "v505",
        external_service_code: "vtp",
        name: "Dịch vụ 5+ gói 500g",
        description: null,
        active: true,
      },
      {
        id: 58,
        code: "leco",
        external_service_code: "vtp",
        name: "Chuyển phát tiết kiệm",
        description: null,
        active: true,
      },
    ],
  },
  {
    id: 6,
    code: "VNP",
    external_service_code: "VNP",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/vietnampost.png",
    name: "VNPost Nhanh",
    active: true,
    transport_types: [],
  },
  {
    id: 7,
    code: "VNPTK",
    external_service_code: "VNPTK",
    logo: null,
    name: "VNPost Tiết Kiệm",
    active: true,
    transport_types: [],
  },
  {
    id: 8,
    code: "JT",
    external_service_code: "JT",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/J%26T+Express.png",
    name: "J&T Express",
    active: true,
    transport_types: [],
  },
  {
    id: 9,
    code: "SE",
    external_service_code: "SE",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/Shopee+Xpress+300+x+50.jpg",
    name: "Shopee Express",
    active: true,
    transport_types: [],
  },
  {
    id: 10,
    code: "GE",
    external_service_code: "GE",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/GrabExpress.png",
    name: "GrabExpress",
    active: true,
    transport_types: [],
  },
  {
    id: 11,
    code: "SEI",
    external_service_code: "SEI",
    logo: null,
    name: "Shopee Express Instant",
    active: true,
    transport_types: [],
  },
  {
    id: 12,
    code: "NV",
    external_service_code: "NV",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/Ninja%2BVan+250x69.png",
    name: "Ninja Van",
    active: true,
    transport_types: [],
  },
  {
    id: 14,
    code: "LEX",
    external_service_code: "LEX",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/Lazada+express.png",
    name: "Lazada Express",
    active: true,
    transport_types: [],
  },
  {
    id: 15,
    code: "SHIP60",
    external_service_code: "SHIP60",
    logo: "https://yody-prd-media.s3.ap-southeast-1.amazonaws.com/images/logo/Ship+60.png",
    name: "Ship 60",
    active: true,
    transport_types: [],
  },
  {
    id: 16,
    code: "SOFPVN",
    external_service_code: "SOFPVN",
    logo: null,
    name: "SOFP VN",
    active: true,
    transport_types: [],
  },
  {
    id: 17,
    code: "B2BVN",
    external_service_code: "B2BVN",
    logo: null,
    name: "B2B VN",
    active: true,
    transport_types: [],
  },
  {
    id: 18,
    code: "AhaMove",
    external_service_code: "AhaMove",
    logo: null,
    name: "AhaMove",
    active: true,
    transport_types: [],
  },
  {
    id: 19,
    code: "GRAB",
    external_service_code: "GRAB",
    logo: null,
    name: "GRAB",
    active: true,
    transport_types: [],
  },
  {
    id: 20,
    code: "LogisthaiVN",
    external_service_code: "LogisthaiVN",
    logo: null,
    name: "Logisthai VN",
    active: true,
    transport_types: [],
  },
  {
    id: 21,
    code: "ILogicVN",
    external_service_code: "ILogicVN",
    logo: null,
    name: "I Logic VN",
    active: true,
    transport_types: [],
  },
  {
    id: 22,
    code: "Vinacapital",
    external_service_code: "Vinacapital",
    logo: null,
    name: "Vinacapital",
    active: true,
    transport_types: [],
  },
  {
    id: 23,
    code: "Cainiao",
    external_service_code: "Cainiao",
    logo: null,
    name: "Cainiao",
    active: true,
    transport_types: [],
  },
  {
    id: 24,
    code: "PickmeeVN",
    external_service_code: "PickmeeVN",
    logo: null,
    name: "PickmeeVN",
    active: true,
    transport_types: [],
  },
  {
    id: 25,
    code: "LGS",
    external_service_code: "LGS",
    logo: null,
    name: "LGS",
    active: true,
    transport_types: [],
  },
  {
    id: 26,
    code: "TED",
    external_service_code: "TED",
    logo: null,
    name: "TED",
    active: true,
    transport_types: [],
  },
  {
    id: 27,
    code: "e-ghn",
    external_service_code: "e-ghn",
    logo: "https://yody-file.s3.ap-southeast-1.amazonaws.com/variant/2021-09-21-22-29-31_47725ba4-779a-426a-9eb9-67b79d8936fe.png",
    name: "Giao hàng nhanh",
    active: true,
    transport_types: [],
  },
  {
    id: 28,
    code: "snappy",
    external_service_code: "snappy",
    logo: "https://cdn.yody.io/images/variant/2022-07-14-08-56-59_1e63d3db-5401-42b7-a4e9-7104638ad65e.jpg",
    name: "Snappy",
    active: true,
    transport_types: [],
  },
];

const requirementNameViewDataTest: any = "Cho xem và thử hàng";
const orderPageTypeDataTest: any = "orderDetail";
handleFixWindowMatchMediaTest();
const setup = (
  deliveryServices: any,
  fulfillment: any,
  requirementNameView: any,
  OrderDetail: any,
  orderPageType: any,
) => {
  render(
    <Provider store={store}>
      <OrderFulfillmentDetail
        deliveryServices={deliveryServices}
        fulfillment={fulfillment}
        requirementNameView={requirementNameView}
        orderDetail={OrderDetail}
        orderPageType={orderPageType}
      />
    </Provider>,
  );
};

describe("Fulfillment Is At Store", () => {
  setup(
    deliveryServicesDataTest,
    fulfillmentDataTest,
    requirementNameViewDataTest,
    orderDetailDataTest,
    orderPageTypeDataTest,
  );
  const storeNameElement = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(1) > div > div.ant-col.ant-col-14 > p > b",
  );
  const storePhone = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(2) > div > div.ant-col.ant-col-14 > p > b",
  );
  const storeAddress = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(3) > div > div.ant-col.ant-col-14 > p > b",
  );

  const orderShippingFee = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(4) > div > div.ant-col.ant-col-14 > p > b",
  );

  const orderShippingType = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(5) > div > div.ant-col.ant-col-14 > p > b",
  );

  const orderCalculateSumWeight = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(6) > div > div.ant-col.ant-col-14 > p > b",
  );

  const orderCreateDate = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(7) > div > div.ant-col.ant-col-14 > p > b",
  );

  const orderRequirement = document.querySelector(
    "#order_fulfillment_detail > div:nth-child(2) > div:nth-child(8) > div > div.ant-col.ant-col-14 > p > b",
  );
  it("Fulfillment Delivered", async () => {
    await waitFor(() => {
      expect(storeNameElement).toBeTruthy();
      expect(storePhone).toBeTruthy();
      expect(storeAddress).toBeTruthy();
      expect(orderShippingFee).toBeTruthy();
      expect(orderShippingType).toBeTruthy();
      expect(orderCalculateSumWeight).toBeTruthy();
      expect(orderCreateDate).toBeTruthy();
      expect(orderRequirement).toBeTruthy();
    });
  });
});
