import { KeyDriverDimension, KeyDriverField } from "model/report";

const {
  TotalSales,
  OfflineTotalSales,
  AverageCustomerSpent,
  AverageOrderValue,
  Visitors,
  ConvertionRate,
  CustomersCount,
  VipTotalSales,
  VipCalls,
  VipCallRate,
  NearVipTotalSales,
  NearVipCalls,
  NearVipCallRate,
  BirthdayTotalSales,
  BirthdayCallConversions,
  BirthdayCalls,
  BirthdayCallRate,
  BirthdaySmsConversions,
  BirthdaySmss,
  BirthdaySmsRate,
  CustomerGt90DaysTotalSales,
  CustomerSmss,
  CustomerSmsRate,
  ShopperGt90DaysTotalSales,
  ShoperSmss,
  ShoperSmsRate,
  NewTotalSales,
  PotentialCustomerCount,
  NewCustomersConversionRate,
  OthersTotalSales,
  FacebookTotalSales,
  ZaloSotalSales,
  UniformTotalSales,
  FollowFanpage,
  UniformOnlineTotalSales,
  ProductTotalSales,
  Profit,
  RevenueSuccess,
  Cost,
  Shipping,
  StorePerformance,
} = KeyDriverField;

const { Asm, Store } = KeyDriverDimension;

// Asm dimension
export const kdOfflineTemplateData: readonly any[] = [
  {
    key: TotalSales,
    name: "Doanh thu",
    method:
      "Doanh thu = Doanh thu bán lẻ + Doanh thu bán hàng Facebook + Doanh thu bán hàng Zalo + Doanh thu đơn đồng phục",
    level: 1,
  },
  {
    key: OfflineTotalSales,
    name: "Doanh thu bán lẻ",
    method: "Doanh thu bán lẻ",
    level: 2,
    parent: TotalSales,
  },
  {
    key: AverageCustomerSpent,
    name: "GTTB / Khách mua",
    level: 3,
    parent: OfflineTotalSales,
  },
  {
    key: AverageOrderValue,
    name: "GTTB / Hoá đơn",
    level: 3,
    parent: OfflineTotalSales,
  },
  {
    key: Visitors,
    name: "Khách vào",
    level: 3,
    parent: OfflineTotalSales,
  },
  {
    key: ConvertionRate,
    name: "Tỷ lệ chuyển đổi",
    suffix: "%",
    level: 3,
    parent: OfflineTotalSales,
  },
  {
    key: CustomersCount,
    name: "Tổng khách mua",
    level: 3,
    parent: OfflineTotalSales,
  },
  {
    key: VipTotalSales,
    name: "VIP",
    method: "(Khách hàng VIP S,G,R,D tích lũy > 10 triệu)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: VipCalls,
    name: "Số cuộc gọi đi",
    method: "",
    level: 5,
    parent: VipTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: VipCallRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 5,
    parent: VipTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: NearVipTotalSales,
    name: "Cận VIP",
    method: "(Khách hàng từ 3 - <10 triệu)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: NearVipCalls,
    name: "Số cuộc gọi đi",
    method: "",
    level: 5,
    parent: NearVipTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: NearVipCallRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 5,
    parent: NearVipTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: BirthdayTotalSales,
    name: "Sinh nhật",
    method: "(Là khách hàng có sinh nhật trong tháng ko bao gồm VIP và Cận VIP)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: BirthdayCallConversions,
    name: "Số khách mua từ cuộc gọi",
    method: "Số khách mua từ cuộc gọi",
    level: 5,
    parent: BirthdayTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: BirthdayCalls,
    name: "Số cuộc gọi đi",
    method: "",
    level: 6,
    parent: BirthdayCallConversions,
    allowedDimension: [Asm, Store],
  },
  {
    key: BirthdayCallRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 6,
    parent: BirthdayCallConversions,
    allowedDimension: [Asm, Store],
  },
  {
    key: BirthdaySmsConversions,
    name: "Số khách mua từ SMS",
    method: "Số khách mua từ SMS",
    level: 5,
    parent: BirthdayTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: BirthdaySmss,
    name: "Số tin nhắn SMS đi",
    method: "",
    level: 6,
    parent: BirthdaySmsConversions,
    allowedDimension: [Asm, Store],
  },
  {
    key: BirthdaySmsRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 6,
    parent: BirthdaySmsConversions,
    allowedDimension: [Asm, Store],
  },
  {
    key: CustomerGt90DaysTotalSales,
    name: "Customer",
    method: "(KH mua 2 lần trở lên, > 90 ngày chưa mua, 3TR > tích lũy >= 200k)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: CustomerSmss,
    name: "Số tin nhắn SMS đi",
    method: "",
    level: 5,
    parent: CustomerGt90DaysTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: CustomerSmsRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 5,
    parent: CustomerGt90DaysTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: ShopperGt90DaysTotalSales,
    name: "Shoper",
    method: "(KH mua 1 lần, > 90 ngày chưa mua, 3TR > tích lũy >= 200k)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: ShoperSmss,
    name: "Số tin nhắn SMS đi",
    method: "",
    level: 5,
    parent: ShopperGt90DaysTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: ShoperSmsRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 5,
    parent: ShopperGt90DaysTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: NewTotalSales,
    name: "Mới",
    method: "(Là data mới toanh)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: PotentialCustomerCount,
    name: "Data KH tiềm năng",
    method: "",
    level: 5,
    parent: NewTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: NewCustomersConversionRate,
    name: "Tỷ lệ chuyển đổi",
    method: "",
    suffix: "%",
    level: 5,
    parent: NewTotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: OthersTotalSales,
    name: "KH còn lại",
    method: "(là KH còn lại ko nằm trong các tệp trên)",
    level: 4,
    parent: CustomersCount,
  },
  {
    key: FacebookTotalSales,
    name: "Doanh thu online Facebook",
    level: 2,
    parent: TotalSales,
  },
  {
    key: ZaloSotalSales,
    name: "Doanh thu online Zalo",
    level: 2,
    parent: TotalSales,
  },
  {
    key: UniformTotalSales,
    name: "Doanh thu đơn đồng phục",
    level: 2,
    parent: TotalSales,
  },
  {
    key: FollowFanpage,
    name: "Lượt follow fanpage",
    level: 2,
    parent: TotalSales,
    allowedDimension: [Asm, Store],
  },
  {
    key: UniformOnlineTotalSales,
    name: "Doanh thu đóng hàng online",
    level: 2,
    parent: TotalSales,
  },
  // {
  //   name: "Doanh thu giao hàng 4h",
  //   method: "Tính năng đang phát triển",
  // },
  {
    key: ProductTotalSales,
    name: "Doanh thu theo sản phẩm",
    method: "Doanh thu theo sản phẩm",
    children: [],
    level: 1,
  },
  {
    key: Profit,
    name: "Lợi nhuận",
    method: "Lợi nhuận",
    level: 1,
    allowedDimension: [Asm, Store],
  },
  {
    key: RevenueSuccess,
    name: "Doanh thu thành công",
    method: "Doanh thu thành công",
    level: 2,
    parent: Profit,
    allowedDimension: [Asm, Store],
  },
  {
    key: Cost,
    name: "Giá vốn",
    method: "Giá vốn",
    level: 2,
    parent: Profit,
    allowedDimension: [Asm, Store],
  },
  {
    key: Shipping,
    name: "Phí thu báo khách của các đơn thành công",
    method: "Phí thu báo khách của các đơn thành công",
    level: 2,
    parent: Profit,
    allowedDimension: [Asm, Store],
  },
  {
    key: StorePerformance,
    name: "Hiệu suất cửa hàng",
    method: "Hiệu suất cửa hàng",
    level: 1,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_stores_avg",
    name: "DTTB/ Cửa hàng",
    method: "DTTB/ Cửa hàng",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_stores",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_stores_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_stores",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_stores_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_squares_avg",
    name: "DTTB/ m2",
    method: "DTTB/ m2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_squares",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_squares_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_squares",
    name: "Tổng số m2",
    method: "Tổng số m2",
    level: 3,
    parent: "total_sales_squares_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_mini1_avg",
    name: "DTTB/ Cửa hàng MINI - 1",
    method: "DTTB/ Cửa hàng MINI - 1",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_mini1",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_mini1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "mini1_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_mini1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_mini2_avg",
    name: "DTTB/ Cửa hàng MINI - 2",
    method: "DTTB/ Cửa hàng MINI - 2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_mini2",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_mini2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "&nbsp;mini2_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_mini2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_mini3_avg",
    name: "DTTB/ Cửa hàng MINI - 3",
    method: "DTTB/ Cửa hàng MINI - 3",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_mini3",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_mini3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "mini3_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_mini3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_s1_avg",
    name: "DTTB/ Cửa hàng S - 1",
    method: "DTTB/ Cửa hàng S - 1",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_s1",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_s1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "s1_number",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_s1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_s2_avg",
    name: "DTTB/ Cửa hàng S - 2",
    method: "DTTB/ Cửa hàng S - 2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_s2",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_s2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "s2_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_s2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_s3_avg",
    name: "DTTB/ Cửa hàng S - 3",
    method: "DTTB/ Cửa hàng S - 3",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_s3",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_s3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "s3_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_s3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_m1_avg",
    name: "DTTB/ Cửa hàng M - 1",
    method: "DTTB/ Cửa hàng M - 1",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_m1",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_m1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "m1_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_m1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_m2_avg",
    name: "DTTB/ Cửa hàng M - 2",
    method: "DTTB/ Cửa hàng M - 2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_m2",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_m2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "m2_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_m2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_m3_avg",
    name: "DTTB/ Cửa hàng M - 3",
    method: "DTTB/ Cửa hàng M - 3",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_m3",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_m3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "m3_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_m3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_l1_avg",
    name: "DTTB/ Cửa hàng L - 1",
    method: "DTTB/ Cửa hàng L - 1",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_l1",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_l1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "l1_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_l1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_l2_avg",
    name: "DTTB/ Cửa hàng L - 2",
    method: "DTTB/ Cửa hàng L - 2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_l2",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_l2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "l2_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_l2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_l3_avg",
    name: "DTTB/ Cửa hàng L - 3",
    method: "DTTB/ Cửa hàng L - 3",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_l3",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_l3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "l3_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_l3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_xl2_avg",
    name: "DTTB/ Cửa hàng XL - 2",
    method: "DTTB/ Cửa hàng XL - 2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_xl2",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_xl2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "xl2_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_xl2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_xl3_avg",
    name: "DTTB/ Cửa hàng XL - 3",
    method: "DTTB/ Cửa hàng XL - 3",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_xl3",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_xl3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "xl3_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_xl3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f1_avg",
    name: "DTTB/ Cửa hàng F - 3.1",
    method: "DTTB/ Cửa hàng F - 3.1",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f1",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_f1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "f1_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_f1_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f2_avg",
    name: "DTTB/ Cửa hàng F - 3.2",
    method: "DTTB/ Cửa hàng F - 3.2",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f2",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_f2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "f2_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_f2_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f3_avg",
    name: "DTTB/ Cửa hàng F - 3.3",
    method: "DTTB/ Cửa hàng F - 3.3",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f3",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_f3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "f3_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_f3_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f4_avg",
    name: "DTTB/ Cửa hàng F - 3.4",
    method: "DTTB/ Cửa hàng F - 3.4",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_f4",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_f4_avg",
    allowedDimension: [Asm],
  },
  {
    key: "f4_numbers",
    name: "Số lượng cửa hàng",
    method: "Số lượng cửa hàng",
    level: 3,
    parent: "total_sales_f4_avg",
    allowedDimension: [Asm],
  },
  {
    key: "total_sales_avg",
    name: "DTTB/ Nhân sự khối cửa hàng",
    method: "DTTB/ Nhân sự khối cửa hàng",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_staffs",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_staffs",
    name: "Số lượng nhân sự",
    method: "Số lượng nhân sự",
    level: 3,
    parent: "total_sales_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_consultants_avg",
    name: "DTTB/ Chuyên gia tư vấn",
    method: "DTTB/ Chuyên gia tư vấn",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_consultants",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_consultants_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "consultant_numbers",
    name: "Số lượng nhân sự",
    method: "Số lượng nhân sự",
    level: 3,
    parent: "total_sales_consultants_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_probationary_consultants_avg",
    name: "DTTB/ Chuyên gia tư vấn thử việc",
    method: "DTTB/ Chuyên gia tư vấn thử việc",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_probationary_consultants",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_probationary_consultants_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "probationary_consultant_numbers",
    name: "Số lượng nhân sự",
    method: "Số lượng nhân sự",
    level: 3,
    parent: "total_sales_probationary_consultants_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_official_consultants_avg",
    name: "DTTB/ Chuyên gia tư vấn chính thức",
    method: "DTTB/ Chuyên gia tư vấn chính thức",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_official_consultants",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_official_consultants_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "official_consultant_numbers",
    name: "Số lượng nhân sự",
    method: "Số lượng nhân sự",
    level: 3,
    parent: "total_sales_official_consultants_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_warehouse_staffs_avg",
    name: "DTTB/ Nhân viên kho",
    method: "DTTB/ Nhân viên kho",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_warehouse_staffs",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_warehouse_staffs_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "warehouse_staff_numbers",
    name: "Số lượng nhân sự",
    method: "Số lượng nhân sự",
    level: 3,
    parent: "total_sales_warehouse_staffs_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_cashier_staffs_avg",
    name: "DTTB/ Nhân viên thu ngân",
    method: "DTTB/ Nhân viên thu ngân",
    level: 2,
    parent: StorePerformance,
    allowedDimension: [Asm, Store],
  },
  {
    key: "total_sales_cashier_staffs",
    name: "Doanh thu",
    method: "Doanh thu",
    level: 3,
    parent: "total_sales_cashier_staffs_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "cashier_staff_number",
    name: "Số lượng nhân sự",
    method: "Số lượng nhân sự",
    level: 3,
    parent: "total_sales_cashier_staffs_avg",
    allowedDimension: [Asm, Store],
  },
  {
    key: "nps",
    name: "Điểm NPS",
    method: "",
    level: 1,
    allowedDimension: [Asm, Store],
  },
  {
    key: "point9_to10",
    name: "Số người đánh giá 9-10",
    method:
      "Số khách hàng đánh giá dịch vụ/sản phẩm của thương hiệu với điểm từ 9/10 đến 10/10. Đơn vị: Số người",
    level: 2,
    parent: "nps",
    allowedDimension: [Asm, Store],
  },
  {
    key: "point7_to8",
    name: "Số người đánh giá 7-8",
    method:
      "Số khách hàng đánh giá dịch vụ/sản phẩm của thương hiệu với điểm từ 7/10 đến 8/10. Đơn vị: Số người ",
    level: 2,
    parent: "nps",
    allowedDimension: [Asm, Store],
  },
  {
    key: "point0_to6",
    name: "Số người đánh giá 0-6",
    method:
      "Số khách hàng đánh giá dịch vụ/sản phẩm của thương hiệu với điểm từ 0/10 đến 6/10. Đơn vị: Số người ",
    level: 2,
    parent: "nps",
    allowedDimension: [Asm, Store],
  },
];

export const ASM_LIST = ["ASM Dương Sơn Tùng", "ASM Nguyễn Văn Ánh", "ASM Đỗ Quang Hiếu"];

export const loadingMessage =
  "Dữ liệu đang được đưa lên báo cáo, có thể mất vài phút để hiển thị. Quý khách vui lòng chờ hệ thống xử lý.";
