
export const fields_order_online = [
  {value: "id", name: "ID"},
  {value: "code", name: "Mã đơn hàng"},
  {value: "type", name: "Loại đơn hàng"},
  {value: "createdDate", name: "Ngày tạo"},
  {value: "created", name: "Người tạo đơn"},
  {value: "companyName", name: "Tên công ty"},
  {value: "channel", name: "Nguồn"},
  {value: "orderType", name: "Loại"},
  {value: "store", name: "Kho lấy hàng"},
  {value: "storeCity", name: "Thành phố"},
  {value: "storeDistrict", name: "Quận huyện"},
  {value: "customerName", name: "Tên khách hàng"},
  {value: "customerCode", name: "Mã khách hàng"},
  {value: "customerPhoneNumber", name: "Số điện thoại"},
  {value: "customerEmail", name: "Email"},
  {value: "customerLevel", name: "Cấp độ khách hàng"},
  {value: "customerBirthday", name: "Sinh nhật"},
  {value: "customerCity", name: "Thành phố"},
  {value: "customerDistrict", name: "Quận huyện"},
  {value: "customerWard", name: "Phường xã"},
  {value: "customerAddress", name: "Địa chỉ"},
  {value: "itemName", name: "Sản phẩm"},
  {value: "gift", name: "Quà tặng kèm"},
  {value: "imei", name: "IMEI"},
  {value: "lot", name: "Lô hàng"},
  {value: "productCode", name: "Mã sản phẩm cha"},
  {value: "productName", name: "Tên sản phẩm cha"},
  {value: "sku", name: "Mã sản phẩm"},
  {value: "itemBarcode", name: "Mã vạch"},
  {value: "itemDiscount", name: "Chiết khấu"},
  {value: "itemWeight", name: "Khối lượng"},
  {value: "itemPrice", name: "Giá"},
  {value: "quantity", name: "Số lượng"},
  {value: "productNote", name: "Ghi chú sản phẩm"},
  {value: "totalWeight", name: "Tổng khối lượng"},
  {value: "totalAmount", name: "Giá trị đơn hàng"},
  {value: "deliveryFee", name: "Phí vận chuyển"},
  {value: "overSizeFee", name: "Phí vượt cân"},
  {value: "insuranceFee", name: "Phí bảo hiểm"},
  {value: "returnFee", name: "Phí chuyển hoàn"},
  {value: "cod", name: "Phí thu tiền hộ (COD)"},
  {value: "shippingFeeInformedToCustomer", name: "Phí ship báo khách"},
  {value: "deliveryProviderName", name: "Hãng vận chuyển"},
  {value: "deliveryProviderService", name: "Dịch vụ vận chuyển"},
  {value: "shippingDays", name: "Số ngày chuyển hàng"},
  {value: "trackingCode", name: "Mã đơn hãng vận chuyển"},
  {value: "goodReceiptId", name: "Biên bản"},
  {value: "bankTransferAmount", name: "Tiền chuyển khoản"},
  {value: "bankInfo", name: "Tài khoản chuyển khoản"},
  {value: "orderDiscount", name: "Tiền chiết khấu / đơn hàng"},
  {value: "deposit", name: "Tiền đặt cọc"},
  {value: "bankDeposit", name: "Tài khoản đặt cọc"},
  {value: "codMoney", name: "Tiền COD"},
  {value: "totalPay", name: "Tổng thu"},
  {value: "cost", name: "Giá vốn"},
  {value: "costOrder", name: "Giá vốn đơn hàng"},
  {value: "unit", name: "Đơn vị tính"},
  {value: "internalNote", name: "Ghi chú nội bộ"},
  {value: "customerNote", name: "Ghi chú của khách"},
  {value: "subStatus", name: "Trạng thái"},
  {value: "reasonCancel", name: "Lý do hủy"},
  {value: "coordinator", name: "Chăm sóc đơn hàng"},
  {value: "finalizedOn", name: "Ngày xác nhận"},
  {value: "shippingOn", name: "Ngày gửi HVC"},
  {value: "shippedOn", name: "Ngày bàn giao"},
  {value: "completedOn", name: "Ngày thành công"},
  {value: "source", name: "Nguồn đơn hàng"},
  {value: "deliveryNote", name: "Ghi chú HVC"},
  {value: "deliveryWeight", name: "Khối lượng HVC( gr)"},
  {value: "coupon", name: "Mã khuyến mại"},
  {value: "orderReturnCode", name: "ID đơn trả"},
  {value: "sttDate", name: "STT Theo ngày"},
  {value: "goodReceipt", name: "Biên bản bàn giao"},
  {value: "affiliate", name: "Mã Affiliate"},
  {value: "customerGroup", name: "Nhóm khách hàng"},
  {value: "vat", name: "VAT"},
  {value: "pointConvertAmount", name: "Tiền tiêu điểm"},
  {value: "tags", name: "Nhãn"},
  {value: "pageuid", name: "pageuid"},
  {value: "reCheckStatus", name: "Trạng thái đối soát"},
  {value: "reCheckDate", name: "Ngày đối soát"},
  {value: "payFor", name: "Thanh toán cho doanh nghiệp"},
  {value: "payDate", name: "Ngày thanh toán cho doanh nghiệp"},
  {value: "assignee", name: "Nhân viên bán hàng"},
  {value: "department", name: "Tên shop"},
  {value: "ecommerceShopName", name: "Tên gian hàng"},
  {value: "referenceCode", name: "Mã tham chiếu"},
];
export const fields_shipment = [
  // {value: "stt", name: "ID"},
  {value: "code", name: "Mã đơn giao"},
  {value: "trackingCode", name: "Mã vận chuyển"},
  {value: "orderCode", name: "Mã đơn hàng"},
  {value: "store", name: "Cửa hàng"},
  {value: "status", name: "Trạng thái"},
  {value: "shipperName", name: "Shipper"},
  {value: "shippingFeePaidToThreePls", name: "Phí giao hàng(đối tác)"},
  {value: "customer", name: "Khách hàng"},
  {value: "deliveryFee", name: "Phí giao hàng(H)"},
  {value: "cod", name: "Tiền thu hộ(COD)"},
  {value: "deliveryServiceNote", name: "Ghi chú HVC"},
];
export const fields_return = [
  {value: "orderReturnCode", name: "Mã đơn trả"},
  {value: "orderCode", name: "Mã đơn hàng"},
  {value: "createdDate", name: "Ngày tạo"},
  {value: "receivedDate", name: "Ngày nhận"},
  {value: "customerName", name: "Khách hàng"},
  {value: "customerEmail", name: "Email"},
  {value: "customerPhoneNumber", name: "SĐT"},

  {value: "sku", name: "Mã sản phẩm"},
  {value: "itemName", name: "Tên sản phẩm"},
  {value: "totalAmount", name: "Giá trị"},
  {value: "returnMethod", name: "Phương thức trả"},
  {value: "store", name: "Cửa hàng"},

];

export const fields_order_offline = [
  {value: "createdDate", name: "Ngày"},
  {value: "id", name: "ID"},
  {value: "code", name: "Mã đơn hàng"},
  {value: "created", name: "NV thu ngân"},
  {value: "assignee", name: "NV bán hàng"},
  {value: "store", name: "Kho"},
  {value: "customerCode", name: "Mã khách hàng"},
  {value: "customerName", name: "Tên khách hàng"},
  {value: "customerBirthday", name: "Ngày sinh khách hàng"},
  {value: "customerPhoneNumber", name: "SĐT khách hàng"},
  {value: "customerEmail", name: "Email khách hàng"},
  {value: "customerAddress", name: "Địa chỉ khách hàng"},
  {value: "customerGroup", name: "Nhóm khách hàng"},
  {value: "itemBarcode", name: "Mã vạch"},
  {value: "sku", name: "Mã sản phẩm"},
  {value: "productCode", name: "Mã sản phẩm cha"},
  {value: "productName", name: "Tên sản phẩm cha"},
  {value: "itemName", name: "Tên sản phẩm"},
  {value: "unit", name: "Đơn vị tính"},
  {value: "itemPrice", name: "Giá bán"},
  {value: "quantity", name: "Số lượng"},
  {value: "productNote", name: "Ghi chú sản phẩm"},
  {value: "itemPriceAfterDiscount", name: "Doanh thu SP sau chiết khấu"},
  {value: "itemDiscount", name: "Chiết khấu"},
  {value: "cash", name: "Tiền mặt"},
  {value: "bankTransferAmount", name: "Chuyển khoản"},
  {value: "cashPay", name: "Tiền khách đưa"},
  {value: "cardAmount", name: "Quẹt thẻ"},
  {value: "qrPayAmount", name: "QR Code"},
  {value: "pointConvertAmount", name: "Tiền tiêu điểm"},
  {value: "totalPay", name: "Tổng tiền"},
  {value: "internalNote", name: "Mô tả"},
  {value: "coupon", name: "Mã coupon"},

];
