import { render } from "@testing-library/react";
import { FormInstance } from "antd";
import { OrderPageTypeModel } from "model/order/order.model";
import { OrderResponse } from "model/response/order/order.response";
import { Provider } from "react-redux";
import {
  handleFixWindowMatchMediaTest,
  mockFunction,
  store,
} from "screens/order-online/utils/test.utils";

import { PAYMENT_METHOD_ENUM } from "utils/Order.constants";
import CardShowOrderPayments from ".";

const testOrderArr: OrderResponse[] | any = [
  // base
  {
    id: 21903712,
    code: "SO021903712",
    version: 1,
    created_by: "YD99999",
    created_name: "Quản trị viên",
    created_date: "2022-10-10T04:10:31Z",
    updated_by: "YD99999",
    updated_name: "Quản trị viên",
    updated_date: "2022-10-10T04:10:31Z",
    reference_code: "",
    company_id: 1,
    company: "Công ty cổ phần thời trang YODY",
    store_id: 78,
    store_code: "YDVNTNN04",
    store: "YODY Sông Công",
    store_phone_number: "0916883258",
    store_full_address: "206 đường cách mạng tháng 8, Cải Đan , thành phố Sông Công , Thái Nguyên",
    status: "finalized",
    price_type: "retail_price",
    tax_treatment: "inclusive",
    source_id: 111,
    source_code: "SC000056",
    source: "CNTT ",
    note: "(123123)",
    tags: "",
    payment_method_id: null,
    payment_method_code: null,
    payment_method: null,
    expected_payment_method_id: null,
    expected_delivery_provider_id: null,
    expected_delivery_type: null,
    customer_note: "",
    sale_note: null,
    account_code: "YD99999",
    account: "Quản trị viên",
    marketer_code: null,
    marketer: null,
    coordinator_code: null,
    coordinator: null,
    assignee_code: "YD8888",
    assignee: "Đỗ Văn Tùng",
    channel_id: 13,
    channel_code: "ADMIN",
    channel: "Admin",
    customer_id: 127296,
    customer: "Đỗ Văn Tùng",
    customer_phone_number: "0973654074",
    customer_email: "",
    fulfillment_status: "unshipped",
    packed_status: null,
    received_status: null,
    payment_status: "partial_paid",
    return_status: "unreturned",
    total_line_amount_after_line_discount: 249000,
    total: 261240,
    order_discount_rate: null,
    order_discount_value: null,
    discount_reason: null,
    total_discount: 9960,
    total_tax: null,
    finalized_account_code: "YD99999",
    cancel_account_code: null,
    finish_account_code: null,
    finalized_on: "2022-10-10T04:10:31.000+00:00",
    cancelled_on: null,
    finished_on: null,
    items: [
      {
        id: 229044,
        code: "fb0d2cab-0646-41a9-8d60-a01f9ca7f805",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        order_line_item_id: null,
        sku: "APM1913.THA_2XL",
        variant_id: 84792,
        variant: "Phông nam cổ tròn melange_Than - 2XL",
        product_id: 22334,
        product: "Phông nam cổ tròn melange_Than",
        product_code: "APM1913.THA",
        variant_barcode: "2000076322332",
        product_type: "normal",
        quantity: 1,
        price: 249000,
        amount: 249000,
        discount_items: [],
        note: "",
        variant_image:
          "https://np-cdn.yody.io/images/variant/2022-09-10-11-24-04_7953e4c2-fcd4-4ea3-acf7-5d21bea50c61.jpeg",
        unit: "piece",
        warranty: null,
        tax_rate: 0,
        tax_include: null,
        is_composite: null,
        line_amount_after_line_discount: 249000,
        discount_rate: 0,
        discount_value: 0,
        discount_amount: 0,
        position: 1,
        weight: 200,
        weight_unit: "g",
        type: "normal",
      },
    ],
    discounts: [
      {
        id: 83827,
        code: "b2d33633-6783-4a0b-a818-57b501876a20",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        rate: 4,
        value: 9960,
        amount: 9960,
        promotion_id: 1537,
        discount_code: null,
        source: null,
        reason: "123123",
        order_id: 21903712,
      },
    ],
    pre_payments: null,
    payments: [
      {
        id: 125315,
        code: "d5858617-9032-4e37-84b7-73539fdae5c6",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        fulfillment_id: null,
        payment_method_id: 1,
        payment_method_code: "point",
        payment_method: "Tiêu điểm",
        amount: 22000,
        reference: "",
        source: "",
        paid_amount: 22000,
        return_amount: 0,
        status: "paid",
        customer_id: null,
        type: "",
        invoice_id: null,
        note: null,
        point: 22,
        bank_account_id: null,
        bank_account_number: null,
        bank_account_holder: null,
        bank_code: null,
        bank_name: null,
        ref_transaction_code: null,
        pay_url: null,
        short_link: null,
        expired_at: null,
      },
      {
        id: 125316,
        code: "3c457762-7357-406f-b595-fab61f58eb23",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        fulfillment_id: null,
        payment_method_id: 2,
        payment_method_code: "cash",
        payment_method: "Tiền mặt",
        amount: 11111,
        reference: "",
        source: "",
        paid_amount: 11111,
        return_amount: 0,
        status: "paid",
        customer_id: null,
        type: "",
        invoice_id: null,
        note: null,
        point: null,
        bank_account_id: null,
        bank_account_number: null,
        bank_account_holder: null,
        bank_code: null,
        bank_name: null,
        ref_transaction_code: "",
        pay_url: null,
        short_link: null,
        expired_at: null,
      },
      {
        id: 125317,
        code: "30e5d469-40ab-419d-adfa-bb6a496f8389",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        fulfillment_id: null,
        payment_method_id: 3,
        payment_method_code: "bank_transfer",
        payment_method: "Chuyển khoản",
        amount: 33333,
        reference: "",
        source: "",
        paid_amount: 33333,
        return_amount: 0,
        status: "paid",
        customer_id: null,
        type: "",
        invoice_id: null,
        note: null,
        point: null,
        bank_account_id: null,
        bank_account_number: null,
        bank_account_holder: null,
        bank_code: null,
        bank_name: null,
        ref_transaction_code: null,
        pay_url: null,
        short_link: null,
        expired_at: null,
      },
      {
        id: 125318,
        code: "7170cf30-a1b8-455d-822f-c05e4c235ad6",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        fulfillment_id: null,
        payment_method_id: 4,
        payment_method_code: "qr_pay",
        payment_method: "QR Pay",
        amount: 4444,
        reference: "",
        source: "",
        paid_amount: 4444,
        return_amount: 0,
        status: "paid",
        customer_id: null,
        type: "",
        invoice_id: null,
        note: null,
        point: null,
        bank_account_id: null,
        bank_account_number: null,
        bank_account_holder: null,
        bank_code: null,
        bank_name: null,
        ref_transaction_code: null,
        pay_url: null,
        short_link: null,
        expired_at: null,
      },
    ],
    fulfillments: [
      {
        id: 149274,
        code: "FM000149274",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-10T04:10:31Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-10T04:10:31Z",
        order_id: 21903712,
        account_code: "YD99999",
        assignee_code: "YD8888",
        delivery_type: "",
        status: "unshipped",
        partner_status: null,
        shipment: {
          id: 73733,
          code: "faf87a6d-418e-419d-ba8e-9d5b987b0412",
          version: 1,
          created_by: "YD99999",
          created_name: "Quản trị viên",
          created_date: "2022-10-10T04:10:31Z",
          updated_by: "YD99999",
          updated_name: "Quản trị viên",
          updated_date: "2022-10-10T04:10:31Z",
          delivery_service_provider_id: 2,
          delivery_service_provider_code: "ghtk",
          delivery_service_provider_name: "Giao hàng tiết kiệm",
          delivery_service_provider_type: "external_service",
          delivery_transport_type: "Đường bộ",
          delivery_service_note: null,
          handover_id: null,
          service: "road",
          who_paid: null,
          fee_type: "",
          fee_base_on: "",
          delivery_fee: null,
          reference_status: "",
          reference_status_explanation: "",
          cancel_reason: "",
          tracking_code: "300356716",
          tracking_url: "",
          received_date: null,
          expected_received_date: null,
          shipping_fee_paid_to_three_pls: 35000,
          sender_address_id: 78,
          sender_address:
            '{"id":78,"code":"YDVNTNN04","name":"YODY Sông Công","rank":1,"rank_name":"H1","square":400.0,"country_id":233,"country_name":"VIETNAM","city_id":43,"city_name":"Tỉnh Thái Nguyên","status":"active","status_name":"Đang hoạt động","zip_code":null,"district_id":519,"district_name":"Thành Phố Sông Công","ward_id":8415,"ward_name":"Phường Cải Đan","address":"206 đường cách mạng tháng 8, Cải Đan , thành phố Sông Công , Thái Nguyên","hotline":"0913212132","manager_code":null,"vm_code":null,"finder_code":null,"mail":null,"number_of_account":null,"reference_id":51083}',
          requirements: "open_try",
          requirements_name: null,
          note_to_shipper:
            "Cho xem và thử hàng, Nếu khách không nhận hàng thì tuyệt đối không thu phí ship của khách.",
          fulfillment_id: 149274,
          cod: 190352,
          shipper_code: "",
          shipper_name: "Nguyễn Văn An",
          pushing_note: "Chờ đẩy thông tin đơn hàng",
          pushing_status: "waiting",
          shipping_address:
            '{"created_by":"YD8888","created_name":"Đỗ Văn Tùng","updated_by":"YD8888","updated_name":"Đỗ Văn Tùng","request_id":null,"operator_kc_id":null,"id":41348,"name":"Mina Nhật Quỳnh","email":null,"phone":"0987654321","second_phone":null,"country_id":233,"country":"VIETNAM","city_id":62,"city":"Tỉnh Hưng Yên","district_id":704,"district":"Huyện Yên Mỹ","ward_id":11310,"ward":"Xã Tân Lập","zip_code":null,"full_address":"Thư Thị "}',
          office_time: null,
          shipper_phone: "0123456985",
          recipient_sort_code: null,
          info_shipper: " - Nguyễn Văn An - 0123456985",
          type_shipment: null,
        },
        billing_address_id: null,
        items: [
          {
            id: 185433,
            code: "27d640e0-8c92-423b-93bb-4dd7fd9e14aa",
            version: 1,
            created_by: "YD99999",
            created_name: "Quản trị viên",
            created_date: "2022-10-10T04:10:31Z",
            updated_by: "YD99999",
            updated_name: "Quản trị viên",
            updated_date: "2022-10-10T04:10:31Z",
            order_line_item_id: 229044,
            product_id: 22334,
            product: "Phông nam cổ tròn melange_Than",
            product_code: "APM1913.THA",
            variant_id: 84792,
            variant: "Phông nam cổ tròn melange_Than - 2XL",
            order_line_item_note: null,
            quantity: 1,
            base_price: null,
            discount_rate: 0,
            discount_value: 0,
            tax_type_id: null,
            tax_rate: 0,
            line_amount: null,
            line_discount_amount: null,
            line_amount_after_line_discount: 249000,
            weight: 200,
            weight_unit: "g",
            sku: "APM1913.THA_2XL",
            variant_barcode: "2000076322332",
            unit: "piece",
          },
        ],
        stock_location_id: 78,
        returned_store_id: 383,
        payment_status: "partial_paid",
        total: 271200,
        total_tax: null,
        total_discount: 0,
        total_quantity: 1,
        stock_out_account_code: null,
        receive_account_code: null,
        cancel_account_code: null,
        receive_cancellation_account_code: null,
        payments: null,
        picked_on: null,
        packed_on: null,
        shipped_on: null,
        export_on: null,
        received_on: null,
        cancel_date: null,
        return_status: "unreturned",
        receive_cancellation_on: null,
        status_before_cancellation: null,
        discount_rate: null,
        discount_value: null,
        discount_amount: null,
        total_line_amount_after_line_discount: 249000,
        returning_on: null,
        sub_reason_name: null,
        sub_reason_id: null,
        reason_id: null,
        sub_reason_detail_id: null,
        reason_name: null,
        sub_reason_detail_name: null,
      },
    ],
    currency: "VND",
    billing_address: null,
    shipping_address: {
      id: 41348,
      code: "a09d2c68-0b62-4961-bf8c-2f4cc67f313f",
      version: 1,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-10-10T04:10:31Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-10T04:10:31Z",
      name: "Mina Nhật Quỳnh",
      email: null,
      phone: "0987654321",
      second_phone: null,
      country: "VIETNAM",
      city_id: 62,
      city: "Tỉnh Hưng Yên",
      district_id: 704,
      district: "Huyện Yên Mỹ",
      ward_id: 11310,
      ward: "Xã Tân Lập",
      zip_code: null,
      full_address: "Thư Thị ",
      channel: null,
    },
    shipping_fee_informed_to_customer: 22200,
    url: "",
    sub_status_id: 2,
    sub_status_code: "awaiting_coordinator_confirmation",
    sub_status: "Mới",
    order_returns: [],
    accumulate_point: null,
    linked_order_code: null,
    ecommerce_shop_id: null,
    ecommerce_shop_name: null,
    order_migration_id: null,
    created_on: "2022-10-10T04:10:31.000+00:00",
    campaign_id: null,
    utm_tracking: null,
    export_bill: false,
    migration_note: null,
    atomic_migration: false,
    actual_quantity: 1,
    sub_reason_name: null,
    sub_reason_id: null,
    reason_id: null,
    automatic_discount: true,
    reason_name: null,
    expect: [
      {
        element:
          "div.paymentDetailMain > div > div:nth-child(1) > div > div > div.orderPaymentItem__left > div > div",
        value: PAYMENT_METHOD_ENUM.point.name,
      },
      {
        element:
          "div.paymentDetailMain > div > div:nth-child(1) > div > div > div.orderPaymentItem__left > span",

        value: "22.000",
      },
      {
        element:
          "div.paymentDetailMain > div > div:nth-child(2) > div > div > div.orderPaymentItem__left > div > div",

        value: PAYMENT_METHOD_ENUM.cash.name,
      },
    ],
  },
];

handleFixWindowMatchMediaTest();

const setup = (orderDetail: OrderResponse | null) => {
  const testForm: FormInstance<any> = {
    scrollToField: jest.fn(),
    getFieldValue: jest.fn(),
    getFieldsValue: jest.fn(),
    getFieldError: jest.fn(),
    getFieldsError: jest.fn(),
    getFieldInstance: jest.fn((opts) => (c: any) => c),
    isFieldTouched: jest.fn(),
    isFieldsTouched: jest.fn(() => true),
    isFieldsValidating: jest.fn((opts) => true),
    resetFields: jest.fn(),
    setFieldsValue: jest.fn(),
    isFieldValidating: jest.fn(),
    setFields: jest.fn(),
    validateFields: jest.fn(),
    submit: jest.fn(),
    __INTERNAL__: {
      itemRef: jest.fn(),
    },
  };
  render(
    <Provider store={store}>
      <CardShowOrderPayments
        OrderDetail={orderDetail}
        setExtraPayments={mockFunction}
        disabledActions={mockFunction}
        disabledBottomActions={true}
        isDisablePostPayment={false}
        isShowPaymentPartialPayment={false}
        isVisibleUpdatePayment={false}
        onPaymentSelect={mockFunction}
        orderPageType={OrderPageTypeModel.orderDetail}
        paymentMethod={0}
        paymentMethods={[]}
        payments={[]}
        setOrderDetail={mockFunction}
        setReload={mockFunction}
        setShowPaymentPartialPayment={mockFunction}
        setVisibleUpdatePayment={mockFunction}
        shipmentMethod={0}
        stepsStatusValue={""}
        totalAmountCustomerNeedToPay={0}
        createPaymentCallback={mockFunction}
        form={testForm}
      />
    </Provider>,
  );
};

const orderDetailNotPayment: any = {
  id: 21903707,
  code: "SO021903707",
  version: 1,
  created_by: "YD99999",
  created_name: "Quản trị viên",
  created_date: "2022-10-08T15:41:00Z",
  updated_by: "YD99999",
  updated_name: "Quản trị viên",
  updated_date: "2022-10-08T15:42:24Z",
  reference_code: "10779444",
  company_id: 1,
  company: "Công ty cổ phần thời trang YODY",
  store_id: 160,
  store_code: "YDVNHDG18",
  store: "Hub Online",
  store_phone_number: "02499966668",
  store_full_address: "Hub Online",
  status: "finalized",
  price_type: "retail_price",
  tax_treatment: "inclusive",
  source_id: 143,
  source_code: "SC000086",
  source: "Mobile App",
  note: "(Đơn hàng COD)",
  tags: "",
  payment_method_id: null,
  payment_method_code: null,
  payment_method: null,
  expected_payment_method_id: null,
  expected_delivery_provider_id: null,
  expected_delivery_type: null,
  customer_note: "",
  sale_note: null,
  account_code: "YD99999",
  account: "Quản trị viên",
  marketer_code: null,
  marketer: null,
  coordinator_code: null,
  coordinator: null,
  assignee_code: "YD0WEB",
  assignee: "Web App Ladipage",
  channel_id: 13,
  channel_code: "ADMIN",
  channel: "Admin",
  customer_id: 7422689,
  customer: "TUY****",
  customer_phone_number: "0365987377",
  customer_email: "",
  fulfillment_status: "unshipped",
  packed_status: null,
  received_status: null,
  payment_status: "unpaid",
  return_status: "unreturned",
  total_line_amount_after_line_discount: 549000,
  total: 571200,
  order_discount_rate: null,
  order_discount_value: null,
  discount_reason: null,
  total_discount: 0,
  total_tax: null,
  finalized_account_code: "YD99999",
  cancel_account_code: null,
  finish_account_code: null,
  finalized_on: "2022-10-08T15:41:00.000+00:00",
  cancelled_on: null,
  finished_on: null,
  items: [
    {
      id: 229036,
      code: "3ac34d1c-49ec-4799-8f7a-aa4dbc779ff3",
      version: 1,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-10-08T15:41:00Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-08T15:41:00Z",
      order_line_item_id: null,
      sku: "AKM4027-XAH-XL",
      variant_id: 2338,
      variant: "Áo khoác nam phối lưng - Xanh - XL",
      product_id: 164,
      product: "Áo khoác nam phối lưng",
      product_code: "AKM4027",
      variant_barcode: "2000174723116",
      product_type: "normal",
      quantity: 1,
      price: 549000,
      amount: 549000,
      discount_items: [],
      note: null,
      variant_image: "",
      unit: "piece",
      warranty: null,
      tax_rate: null,
      tax_include: null,
      is_composite: null,
      line_amount_after_line_discount: 549000,
      discount_rate: 0,
      discount_value: 0,
      discount_amount: 0,
      position: null,
      weight: 180,
      weight_unit: "g",
      type: "normal",
    },
  ],
  discounts: [],
  pre_payments: null,
  payments: [],
  fulfillments: [
    {
      id: 149267,
      code: "FM000149267",
      version: 1,
      created_by: "YD99999",
      created_name: "Quản trị viên",
      created_date: "2022-10-08T15:41:00Z",
      updated_by: "YD99999",
      updated_name: "Quản trị viên",
      updated_date: "2022-10-08T15:42:24Z",
      order_id: 21903707,
      account_code: "YD99999",
      assignee_code: "YD0WEB",
      delivery_type: "",
      status: "unshipped",
      partner_status: null,
      shipment: null,
      billing_address_id: null,
      items: [
        {
          id: 185426,
          code: "5ec7ba16-f591-4d94-b141-0d458e1e3799",
          version: 1,
          created_by: "YD99999",
          created_name: "Quản trị viên",
          created_date: "2022-10-08T15:41:00Z",
          updated_by: "YD99999",
          updated_name: "Quản trị viên",
          updated_date: "2022-10-08T15:42:24Z",
          order_line_item_id: 229036,
          product_id: 164,
          product: "Áo khoác nam phối lưng",
          product_code: "AKM4027",
          variant_id: 2338,
          variant: "Áo khoác nam phối lưng - Xanh - XL",
          order_line_item_note: null,
          quantity: 1,
          base_price: null,
          discount_rate: 0,
          discount_value: 0,
          tax_type_id: null,
          tax_rate: null,
          line_amount: null,
          line_discount_amount: null,
          line_amount_after_line_discount: 549000,
          weight: 180,
          weight_unit: "g",
          sku: "AKM4027-XAH-XL",
          variant_barcode: "2000174723116",
          unit: "piece",
        },
      ],
      stock_location_id: 160,
      returned_store_id: 160,
      payment_status: "",
      total: 571200,
      total_tax: null,
      total_discount: 0,
      total_quantity: 1,
      stock_out_account_code: null,
      receive_account_code: null,
      cancel_account_code: null,
      receive_cancellation_account_code: null,
      payments: null,
      picked_on: null,
      packed_on: null,
      shipped_on: null,
      export_on: null,
      received_on: null,
      cancel_date: null,
      return_status: "unreturned",
      receive_cancellation_on: null,
      status_before_cancellation: null,
      discount_rate: null,
      discount_value: null,
      discount_amount: null,
      total_line_amount_after_line_discount: 549000,
      returning_on: null,
      sub_reason_name: null,
      sub_reason_id: null,
      reason_id: null,
      sub_reason_detail_id: null,
      reason_name: null,
      sub_reason_detail_name: null,
    },
  ],
  currency: "VND",
  billing_address: null,
  shipping_address: {
    id: 51772,
    code: "f717893f-c03d-4e69-b8d6-21930cbc0e9a",
    version: 2,
    created_by: "YD99999",
    created_name: "Quản trị viên",
    created_date: "2022-10-08T15:41:00Z",
    updated_by: "YD99999",
    updated_name: "Quản trị viên",
    updated_date: "2022-10-08T15:42:24Z",
    name: "TUY****",
    email: "",
    phone: "0365987377",
    second_phone: "",
    country: null,
    city_id: 47,
    city: "Tỉnh Bắc Giang",
    district_id: 562,
    district: "Huyện Việt Yên",
    ward_id: 9234,
    ward: "Xã Quảng Minh",
    zip_code: null,
    full_address: "Quảng minh, việt yên , bắc giang ",
    channel: null,
  },
  shipping_fee_informed_to_customer: 22200,
  url: "",
  sub_status_id: 2,
  sub_status_code: "awaiting_coordinator_confirmation",
  sub_status: "Mới",
  order_returns: [],
  accumulate_point: null,
  linked_order_code: null,
  ecommerce_shop_id: null,
  ecommerce_shop_name: null,
  order_migration_id: null,
  created_on: "2022-10-08T15:41:00.000+00:00",
  campaign_id: null,
  utm_tracking: null,
  export_bill: false,
  migration_note: null,
  atomic_migration: false,
  actual_quantity: 1,
  sub_reason_name: null,
  sub_reason_id: null,
  reason_id: null,
  automatic_discount: false,
  reason_name: null,
};

describe("test chi tiết đơn hàng thanh toán", () => {
  testOrderArr.map((single: any) => {
    return it(`test tiền mặt ${single.id}`, async () => {
      setup(single);
      let result3 = single.expect.map((expect: any) => {
        let element = document.querySelector(expect.element);
        // console.log("element333", element);
        return element?.innerHTML.includes(expect.value);
      });
      let result = result3.some((single: boolean) => single === false);
      console.log("result", result);
      return expect(result).not.toBeTruthy();
    });
  });
  it(`test chưa thanh toán`, () => {
    setup(orderDetailNotPayment);
    let element = document.querySelector(
      ".orders-update-payment div > button.showCreatePaymentButton__button > span",
    );
    return expect(element?.innerHTML).toEqual("Thanh toán");
  });
});
