const ServiceNames = {
  CONTENT_SERVICE: "content-service",
  PRODUCT_SERVICE: "product-service",
  CORE_SERVICE: "core-service",
  ACCOUNT_SERVICE: "account-service",
  ORDER_SERVICE: "order-service",
  CUSTOMER_SERVICE: "customer-service",
  MARKETING_SERVICE: "marketing-service",
  AUTH_SERVICE: "auth-service",
  PURCHASE_ORDER_SERVICE: "purchase-order-service",
  IMPORT_EXPORT_SERVICE: "import-export-service",
  INVENTORY_SERVICE: "inventory-service",
  INVENTORY_TRANSFER_SERVICE: "inventory-transfer-service",
  LOYALTY_SERVICE: "loyalty-service",
  ECOMMERCE_SERVICE: "ecommerce-service",
  WEBSITE_SERVICE: "website-service",
  LOGISTIC_GATEWAY_SERVICE: "logistic-gateway-service",
  INVENTORY_ADJUSTMENT_SERVICE: "inventory-adjustment-service",
  PROMOTION_SERVICE: "promotion-service",
  KEY_DRIVER_SERVICE: "key-drivers",
  KD_OFFLINE_TOTAL_SALES_SERVICE: "key-drivers/offline-total-sales/v2",
  OFFLINE_TOTAL_SALES_LOYALTY_LEVEL_SERVICE: "key-drivers/offline-total-sales-by-loyalty-level",
  KD_CUSTOMER_VISITORS_SERVICE: "customer-visitors/key-drivers/sum",
  KD_OFFLINE_ONLINE_TOTAL_SALES_SERVICE: "key-drivers/offline-uniform-online-total-sales",
  CUSTOMER_COUNTERS_SERVICE: "customer-counters",
  POTENTIAL_CUSTOMER_REGISTED_SERVICE: "potential-customers/import-customer-registered-for-gift",
  POTENTIAL_CUSTOMER_BOUGHT_SERVICE: "potential-customers/import-bought-potential-customers",
  OFFLINE_TOTAL_SALES_POTENTIAL_SERVICE: "potential-customers/count-by-asm",
  HANDOVER_SERVICE: "handover-service",
  DAILY_PAYMENT_SERVICE: "api/daily-payments",
  OFFLINE_CALL_LOYALTY_LEVEL_SERVICE: "key-drivers/offline-call-conversion-rate-by-loyalty-level",
  OFFLINE_SMS_LOYALTY_LEVEL_SERVICE: "key-drivers/offline-sms-conversion-rate-by-loyalty-level",
};

const v1 = ``;

const ApiConfig = {
  CONTENT: `${v1}/${ServiceNames.CONTENT_SERVICE}`,
  PRODUCT: `${v1}/${ServiceNames.PRODUCT_SERVICE}`,
  CORE: `${v1}/${ServiceNames.CORE_SERVICE}`,
  ACCOUNTS: `${v1}/${ServiceNames.ACCOUNT_SERVICE}`,
  ORDER: `${v1}/${ServiceNames.ORDER_SERVICE}`,
  CUSTOMER: `${v1}/${ServiceNames.CUSTOMER_SERVICE}`,
  MARKETING: `${v1}/${ServiceNames.MARKETING_SERVICE}`,
  AUTH: `${v1}/${ServiceNames.AUTH_SERVICE}`,
  PURCHASE_ORDER: `${v1}/${ServiceNames.PURCHASE_ORDER_SERVICE}`,
  IMPORT_EXPORT: `${v1}/${ServiceNames.IMPORT_EXPORT_SERVICE}`,
  INVENTORY: `${v1}/${ServiceNames.INVENTORY_SERVICE}`,
  INVENTORY_TRANSFER: `${v1}/${ServiceNames.INVENTORY_TRANSFER_SERVICE}`,
  LOYALTY: `${v1}/${ServiceNames.LOYALTY_SERVICE}`,
  ECOMMERCE: `${v1}/${ServiceNames.ECOMMERCE_SERVICE}`,
  WEB_APP: `${v1}/${ServiceNames.WEBSITE_SERVICE}`,
  LOGISTIC_GATEWAY: `${v1}/${ServiceNames.LOGISTIC_GATEWAY_SERVICE}`,
  INVENTORY_ADJUSTMENT: `${v1}/${ServiceNames.INVENTORY_ADJUSTMENT_SERVICE}`,
  PROMOTION: `${v1}/${ServiceNames.PROMOTION_SERVICE}`,
  ANALYTICS: `${v1}/reports`,
  CUSTOMER_VISITORS: `${v1}/customer-visitors`,
  WARRANTY: `${v1}/warranty-service`,
  DASHBOARD: `${v1}/dashboard-service`,
  KEY_DRIVER: `${v1}/${ServiceNames.KEY_DRIVER_SERVICE}`,
  KD_OFFLINE_TOTAL_SALES: `${v1}/${ServiceNames.KD_OFFLINE_TOTAL_SALES_SERVICE}`,
  OFFLINE_TOTAL_SALES_LOYALTY_LEVEL: `${v1}/${ServiceNames.OFFLINE_TOTAL_SALES_LOYALTY_LEVEL_SERVICE}`,
  KD_CUSTOMER_VISITORS: `${v1}/${ServiceNames.KD_CUSTOMER_VISITORS_SERVICE}`,
  KD_OFFLINE_ONLINE_TOTAL_SALES: `${v1}/${ServiceNames.KD_OFFLINE_ONLINE_TOTAL_SALES_SERVICE}`,
  CUSTOMER_COUNTERS: `${v1}/${ServiceNames.CUSTOMER_COUNTERS_SERVICE}`,
  POTENTIAL_CUSTOMER_REGISTED: `${v1}/${ServiceNames.POTENTIAL_CUSTOMER_REGISTED_SERVICE}`,
  POTENTIAL_CUSTOMER_BOUGHT: `${v1}/${ServiceNames.POTENTIAL_CUSTOMER_BOUGHT_SERVICE}`,
  OFFLINE_TOTAL_SALES_POTENTIAL: `${v1}/${ServiceNames.OFFLINE_TOTAL_SALES_POTENTIAL_SERVICE}`,
  HANDOVER: `${v1}/${ServiceNames.HANDOVER_SERVICE}`,
  DAILY_PAYMENT: `${v1}/${ServiceNames.DAILY_PAYMENT_SERVICE}`,
  OFFLINE_CALL_LOYALTY_LEVEL: `${v1}/${ServiceNames.OFFLINE_CALL_LOYALTY_LEVEL_SERVICE}`,
  OFFLINE_SMS_LOYALTY_LEVEL: `${v1}/${ServiceNames.OFFLINE_SMS_LOYALTY_LEVEL_SERVICE}`,
};

export { ApiConfig };
