import { FormInstance } from "antd";
import { OrderResponse } from "model/response/order/order.response";
import configureStore from "redux-mock-store";

export const handleFixWindowMatchMediaTest = () => {
  return Object.defineProperty(window, "matchMedia", {
    writable: true,
    value: (query: any) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: jest.fn(), // deprecated
      removeListener: jest.fn(), // deprecated
      addEventListener: jest.fn(),
      removeEventListener: jest.fn(),
      dispatchEvent: jest.fn(),
    }),
  });
};

const initialState = {};
export const mockStore = configureStore();
export const store = mockStore(initialState);
export const mockFunction = jest.fn;

export const testForm: FormInstance<any> = {
  scrollToField: jest.fn(),
  getFieldValue: jest.fn(),
  getFieldsValue: jest.fn(),
  getFieldError: jest.fn(),
  getFieldsError: jest.fn(),
  getFieldInstance: jest.fn((opts) => (c: any) => c),
  isFieldTouched: jest.fn(),
  isFieldsTouched: jest.fn(() => true),
  isFieldsValidating: jest.fn((opts) => true),
  resetFields: jest.fn(),
  setFieldsValue: jest.fn(),
  isFieldValidating: jest.fn(),
  setFields: jest.fn(),
  validateFields: jest.fn(),
  submit: jest.fn(),
  __INTERNAL__: {
    itemRef: jest.fn(),
  },
};

export const testOrderArr: OrderResponse[] | any = [
  // base
  {
    id: 21903356,
    code: "SO021903356",
    version: 1,
    created_by: "YD8888",
    created_name: "Đỗ Văn Tùng",
    created_date: "2022-10-03T04:20:44Z",
    updated_by: "YD8888",
    updated_name: "Đỗ Văn Tùng",
    updated_date: "2022-10-03T04:21:52Z",
    reference_code: "",
    company_id: 1,
    company: "Công ty cổ phần thời trang YODY",
    store_id: 78,
    store_code: "YDVNTNN04",
    store: "YODY Sông Công",
    store_phone_number: "0916883258",
    store_full_address: "206 đường cách mạng tháng 8, Cải Đan , thành phố Sông Công , Thái Nguyên",
    status: "finalized",
    price_type: "retail_price",
    tax_treatment: "inclusive",
    source_id: 111,
    source_code: "SC000056",
    source: "CNTT ",
    note: "",
    tags: "",
    payment_method_id: null,
    payment_method_code: null,
    payment_method: null,
    expected_payment_method_id: null,
    expected_delivery_provider_id: null,
    expected_delivery_type: null,
    customer_note: "",
    sale_note: null,
    account_code: "YD8888",
    account: "Đỗ Văn Tùng",
    marketer_code: null,
    marketer: null,
    coordinator_code: null,
    coordinator: null,
    assignee_code: "YD8888",
    assignee: "Đỗ Văn Tùng",
    channel_id: 13,
    channel_code: "ADMIN",
    channel: "Admin",
    customer_id: 127296,
    customer: "Đỗ Văn Tùng",
    customer_phone_number: "0973654074",
    customer_email: "",
    fulfillment_status: "unshipped",
    packed_status: null,
    received_status: null,
    payment_status: "paid",
    return_status: "unreturned",
    total_line_amount_after_line_discount: 249000,
    total: 271200,
    order_discount_rate: null,
    order_discount_value: null,
    discount_reason: null,
    total_discount: 0,
    total_tax: null,
    finalized_account_code: "Đỗ Văn Tùng",
    cancel_account_code: null,
    finish_account_code: null,
    finalized_on: "2022-10-03T04:20:49.000+00:00",
    cancelled_on: null,
    finished_on: null,
    items: [
      {
        id: 228195,
        code: "664006cc-dc7c-4e15-9128-bc7498527a22",
        version: 1,
        created_by: "YD8888",
        created_name: "Đỗ Văn Tùng",
        created_date: "2022-10-03T04:20:44Z",
        updated_by: "YD8888",
        updated_name: "Đỗ Văn Tùng",
        updated_date: "2022-10-03T04:20:44Z",
        order_line_item_id: null,
        sku: "APM1913.THA_2XL",
        variant_id: 84792,
        variant: "Phông nam cổ tròn melange_Than - 2XL",
        product_id: 22334,
        product: "Phông nam cổ tròn melange_Than",
        product_code: "APM1913.THA",
        variant_barcode: "2000076322332",
        product_type: "normal",
        quantity: 1,
        price: 249000,
        amount: 249000,
        discount_items: [],
        note: "",
        variant_image:
          "https://np-cdn.yody.io/images/variant/2022-09-10-11-24-04_7953e4c2-fcd4-4ea3-acf7-5d21bea50c61.jpeg",
        unit: "piece",
        warranty: null,
        tax_rate: 0,
        tax_include: null,
        is_composite: null,
        line_amount_after_line_discount: 249000,
        discount_rate: 0,
        discount_value: 0,
        discount_amount: 0,
        position: 1,
        weight: 200,
        weight_unit: "g",
        type: "normal",
      },
    ],
    discounts: [],
    pre_payments: null,
    payments: [
      {
        id: 124994,
        code: "8309618e-407b-494e-bd70-01d8641af959",
        version: 1,
        created_by: "YD8888",
        created_name: "Đỗ Văn Tùng",
        created_date: "2022-10-03T04:21:01Z",
        updated_by: "YD8888",
        updated_name: "Đỗ Văn Tùng",
        updated_date: "2022-10-03T04:21:01Z",
        fulfillment_id: null,
        payment_method_id: 2,
        payment_method_code: "cash",
        payment_method: "Tiền mặt",
        amount: 271200,
        reference: "",
        source: "",
        paid_amount: 271200,
        return_amount: 0,
        status: "paid",
        customer_id: null,
        type: "",
        invoice_id: null,
        note: null,
        point: null,
        bank_account_id: null,
        bank_account_number: null,
        bank_account_holder: null,
        bank_code: null,
        bank_name: null,
        ref_transaction_code: null,
        pay_url: null,
        short_link: null,
        expired_at: null,
      },
    ],
    fulfillments: [
      {
        id: 148908,
        code: "FM000148908",
        version: 1,
        created_by: "Đỗ Văn Tùng",
        created_name: "atung",
        created_date: "2022-10-03T04:20:49Z",
        updated_by: "YD8888",
        updated_name: "Đỗ Văn Tùng",
        updated_date: "2022-10-03T04:21:52Z",
        order_id: 21903356,
        account_code: "YD8888",
        assignee_code: "YD8888",
        delivery_type: null,
        status: "cancelled",
        partner_status: null,
        shipment: {
          id: 73558,
          code: "d8fa9f4f-4762-4aab-9787-2d3cbdca7ff3",
          version: 2,
          created_by: "YD8888",
          created_name: "Đỗ Văn Tùng",
          created_date: "2022-10-03T04:21:11Z",
          updated_by: "YD8888",
          updated_name: "Đỗ Văn Tùng",
          updated_date: "2022-10-03T04:21:52Z",
          delivery_service_provider_id: 2,
          delivery_service_provider_code: "ghtk",
          delivery_service_provider_name: "Giao hàng tiết kiệm",
          delivery_service_provider_type: "external_service",
          delivery_transport_type: "Đường bộ",
          delivery_service_note: null,
          handover_id: null,
          service: "road",
          who_paid: null,
          fee_type: null,
          fee_base_on: null,
          delivery_fee: null,
          reference_status: null,
          reference_status_explanation: null,
          cancel_reason: "customer_cancel",
          tracking_code: "300355948",
          tracking_url: null,
          received_date: null,
          expected_received_date: null,
          shipping_fee_paid_to_three_pls: 35000,
          sender_address_id: 78,
          sender_address:
            '{"id":78,"code":"YDVNTNN04","name":"YODY Sông Công","rank":1,"rank_name":"H1","square":400.0,"country_id":233,"country_name":"VIETNAM","city_id":43,"city_name":"Tỉnh Thái Nguyên","status":"active","status_name":"Đang hoạt động","zip_code":null,"district_id":519,"district_name":"Thành Phố Sông Công","ward_id":8415,"ward_name":"Phường Cải Đan","address":"206 đường cách mạng tháng 8, Cải Đan , thành phố Sông Công , Thái Nguyên","hotline":"0913212132","manager_code":null,"vm_code":null,"finder_code":null,"mail":null,"number_of_account":null,"reference_id":51083}',
          requirements: "open_try",
          requirements_name: null,
          note_to_shipper:
            "Cho xem và thử hàng, Nếu khách không nhận hàng thì tuyệt đối không thu phí ship của khách.",
          fulfillment_id: 148908,
          cod: 0,
          shipper_code: null,
          shipper_name: null,
          pushing_note: "Chờ đẩy thông tin đơn hàng",
          pushing_status: "waiting",
          shipping_address:
            '{"id":41348,"code":"e81edca8-6dc5-4839-92b3-5b9bae82c40f","version":3,"created_by":"YD8888","created_name":"Đỗ Văn Tùng","updated_by":"YD8888","updated_name":"Đỗ Văn Tùng","created_date":1664770844000,"updated_date":1664770861000,"events":[],"order_id":21903356,"name":"Mina Nhật Quỳnh","email":null,"phone":"0987654321","second_phone":"","country_id":233,"country":"VIETNAM","city_id":62,"city":"Tỉnh Hưng Yên","district_id":704,"district":"Huyện Yên Mỹ","ward_id":11310,"ward":"Xã Tân Lập","zip_code":null,"full_address":"Thư Thị ","deleted":false}',
          office_time: null,
          shipper_phone: null,
          recipient_sort_code: null,
          info_shipper: null,
          type_shipment: null,
        },
        billing_address_id: null,
        items: [
          {
            id: 184676,
            code: "caadd2b3-b9fa-415f-9060-03490bee65f7",
            version: 1,
            created_by: "Đỗ Văn Tùng",
            created_name: "atung",
            created_date: "2022-10-03T04:20:49Z",
            updated_by: "Đỗ Văn Tùng",
            updated_name: "atung",
            updated_date: "2022-10-03T04:20:49Z",
            order_line_item_id: 228195,
            product_id: 22334,
            product: "Phông nam cổ tròn melange_Than",
            product_code: "APM1913.THA",
            variant_id: 84792,
            variant: "Phông nam cổ tròn melange_Than - 2XL",
            order_line_item_note: null,
            quantity: 1,
            base_price: null,
            discount_rate: 0,
            discount_value: 0,
            tax_type_id: null,
            tax_rate: 0,
            line_amount: null,
            line_discount_amount: null,
            line_amount_after_line_discount: 249000,
            weight: 200,
            weight_unit: "g",
            sku: "APM1913.THA_2XL",
            variant_barcode: "2000076322332",
            unit: "piece",
          },
        ],
        stock_location_id: 78,
        returned_store_id: 383,
        payment_status: "paid",
        total: 271200,
        total_tax: null,
        total_discount: 0,
        total_quantity: 1,
        stock_out_account_code: null,
        receive_account_code: null,
        cancel_account_code: null,
        receive_cancellation_account_code: null,
        payments: null,
        picked_on: null,
        packed_on: null,
        shipped_on: null,
        export_on: null,
        received_on: null,
        cancel_date: "2022-10-03T04:21:52.000+00:00",
        return_status: "unreturned",
        receive_cancellation_on: null,
        status_before_cancellation: "unshipped",
        discount_rate: null,
        discount_value: null,
        discount_amount: null,
        total_line_amount_after_line_discount: 249000,
        returning_on: null,
        sub_reason_id: 1,
        reason_id: 2,
        sub_reason_detail_id: null,
        reason_name: "Khách huỷ",
        sub_reason_detail_name: null,
        sub_reason_name: "Đặt nhầm sản phẩm",
      },
      {
        id: 148910,
        code: "FM000148910",
        version: 1,
        created_by: "YD8888",
        created_name: "Đỗ Văn Tùng",
        created_date: "2022-10-03T04:21:52Z",
        updated_by: "YD8888",
        updated_name: "Đỗ Văn Tùng",
        updated_date: "2022-10-03T04:21:52Z",
        order_id: 21903356,
        account_code: "YD8888",
        assignee_code: "YD8888",
        delivery_type: null,
        status: "unshipped",
        partner_status: null,
        shipment: null,
        billing_address_id: null,
        items: [
          {
            id: 184678,
            code: "3db09822-d795-44e7-8d35-b657453d372a",
            version: 1,
            created_by: "YD8888",
            created_name: "Đỗ Văn Tùng",
            created_date: "2022-10-03T04:21:52Z",
            updated_by: "YD8888",
            updated_name: "Đỗ Văn Tùng",
            updated_date: "2022-10-03T04:21:52Z",
            order_line_item_id: 228195,
            product_id: 22334,
            product: "Phông nam cổ tròn melange_Than",
            product_code: "APM1913.THA",
            variant_id: 84792,
            variant: "Phông nam cổ tròn melange_Than - 2XL",
            order_line_item_note: null,
            quantity: 1,
            base_price: null,
            discount_rate: 0,
            discount_value: 0,
            tax_type_id: null,
            tax_rate: 0,
            line_amount: null,
            line_discount_amount: null,
            line_amount_after_line_discount: 249000,
            weight: 200,
            weight_unit: "g",
            sku: "APM1913.THA_2XL",
            variant_barcode: "2000076322332",
            unit: "piece",
          },
        ],
        stock_location_id: 78,
        returned_store_id: 78,
        payment_status: "paid",
        total: 271200,
        total_tax: null,
        total_discount: 0,
        total_quantity: 1,
        stock_out_account_code: null,
        receive_account_code: null,
        cancel_account_code: null,
        receive_cancellation_account_code: null,
        payments: null,
        picked_on: null,
        packed_on: null,
        shipped_on: null,
        export_on: null,
        received_on: null,
        cancel_date: null,
        return_status: "unreturned",
        receive_cancellation_on: null,
        status_before_cancellation: null,
        discount_rate: null,
        discount_value: null,
        discount_amount: null,
        total_line_amount_after_line_discount: 249000,
        returning_on: null,
        sub_reason_id: null,
        reason_id: null,
        sub_reason_detail_id: null,
        reason_name: null,
        sub_reason_detail_name: null,
        sub_reason_name: null,
      },
    ],
    currency: "VND",
    billing_address: null,
    shipping_address: {
      id: 41348,
      code: "e81edca8-6dc5-4839-92b3-5b9bae82c40f",
      version: 5,
      created_by: "YD8888",
      created_name: "Đỗ Văn Tùng",
      created_date: "2022-10-03T04:20:44Z",
      updated_by: "YD8888",
      updated_name: "Đỗ Văn Tùng",
      updated_date: "2022-10-03T04:21:52Z",
      name: "Mina Nhật Quỳnh",
      email: null,
      phone: "0987654321",
      second_phone: "",
      country: "VIETNAM",
      city_id: 62,
      city: "Tỉnh Hưng Yên",
      district_id: 704,
      district: "Huyện Yên Mỹ",
      ward_id: 11310,
      ward: "Xã Tân Lập",
      zip_code: null,
      full_address: "Thư Thị ",
      channel: null,
    },
    shipping_fee_informed_to_customer: 22200,
    url: "",
    sub_status_id: 20,
    sub_status_code: "coordinator_confirming",
    sub_status: "Đang xác nhận",
    order_returns: [],
    accumulate_point: null,
    linked_order_code: null,
    ecommerce_shop_id: null,
    ecommerce_shop_name: null,
    order_migration_id: null,
    created_on: "2022-10-03T04:20:44.000+00:00",
    campaign_id: null,
    utm_tracking: null,
    export_bill: false,
    migration_note: null,
    atomic_migration: false,
    actual_quantity: 1,
    sub_reason_id: null,
    reason_id: null,
    automatic_discount: true,
    reason_name: null,
    sub_reason_name: null,
  },
];
