import { render, waitFor } from "@testing-library/react";
import { Provider } from "react-redux";
import { handleFixWindowMatchMediaTest, store } from "screens/order-online/utils/test.utils";
import OrderFulfillmentShowProduct from ".";

const orderDetailDataTest: any = {
  id: 21903828,
  code: "SO021903828",
  version: 1,
  created_by: "YD15143T",
  created_name: "Thoa Test",
  created_date: "2022-10-13T04:53:29Z",
  updated_by: "YD99999",
  updated_name: "Quản trị viên",
  updated_date: "2022-10-13T06:12:46Z",
  reference_code: "",
  company_id: 1,
  company: "Công ty cổ phần thời trang YODY",
  store_id: 2,
  store_code: "YDVNHTH01",
  store: "YODY Đức Thọ",
  store_phone_number: "18002086",
  store_full_address: "Từ Ô, Tân Trào, Thanh Miện District, Hai Duong, Vietnam",
  status: "finished",
  price_type: "retail_price",
  tax_treatment: "inclusive",
  source_id: 257,
  source_code: "SC000324",
  source: "test chicken 14",
  note: "(đơn hàng 4)",
  tags: "",
  payment_method_id: null,
  payment_method_code: null,
  payment_method: null,
  expected_payment_method_id: null,
  expected_delivery_provider_id: null,
  expected_delivery_type: null,
  customer_note: "",
  sale_note: null,
  account_code: "YD15143T",
  account: "Thoa Test",
  marketer_code: null,
  marketer: null,
  coordinator_code: null,
  coordinator: null,
  assignee_code: "YD15143T",
  assignee: "Thoa Test",
  channel_id: 13,
  channel_code: "ADMIN",
  channel: "Admin",
  customer_id: 7097265,
  customer: "Nguyễn",
  customer_phone_number: "0988467460",
  customer_email: null,
  fulfillment_status: "shipped",
  packed_status: null,
  received_status: null,
  payment_status: "paid",
  return_status: "returning",
  total_line_amount_after_line_discount: 3200000,
  total: 3199000,
  order_discount_rate: null,
  order_discount_value: null,
  discount_reason: null,
  total_discount: 32000,
  total_tax: null,
  finalized_account_code: "YD15143T",
  cancel_account_code: null,
  finish_account_code: null,
  finalized_on: "2022-10-13T04:53:29.000+00:00",
  cancelled_on: null,
  finished_on: "2022-10-13T04:53:46.000+00:00",
  items: [
    {
      id: 229241,
      code: "1f96e7c2-6e9f-4489-83f6-12f1ead555d8",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T04:53:29Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T04:53:29Z",
      order_line_item_id: null,
      sku: "MAI1234-DDO-XL1",
      variant_id: 98539,
      variant:
        "Áo Chống Nắng - Đỏ - Xl1 Vụ Việc Xảy Ra Tại Công Ty Cổ Phần Tập Đoàn Đầu Tư An Đông (liên Quan Bắt Chủ Tịch Tập Đoàn Vạn Thịnh Phát) Và Các Tổ Chức, Đơn Vị Có Liên Quan Đang Được Xã Hội, Người Dân Rất Quan Tâm.",
      product_id: 59727,
      product: "Áo Chống Nắng",
      product_code: "MAI1234",
      variant_barcode: "2900000985391",
      product_type: "normal",
      quantity: 1,
      price: 200000,
      amount: 200000,
      discount_items: [],
      note: "",
      variant_image:
        "https://np-cdn.yody.io/images/variant/2022-10-10-10-22-06_a96ed57f-0e27-4048-ac36-62153ba60c60.jpg",
      unit: "piece",
      warranty: "wash-60-mild;wash-70;",
      tax_rate: 10,
      tax_include: null,
      is_composite: null,
      line_amount_after_line_discount: 200000,
      discount_rate: 0,
      discount_value: 0,
      discount_amount: 0,
      position: 2,
      weight: 24,
      weight_unit: "g",
      type: "normal",
    },
    {
      id: 229242,
      code: "5313154f-1034-435a-b70d-afe67f21c3a4",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T04:53:29Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T04:53:29Z",
      order_line_item_id: null,
      sku: "AOS2222",
      variant_id: 98665,
      variant: "Áo Chống Nắng Yooody",
      product_id: 59771,
      product: "Áo Chống Nắng Yooody",
      product_code: "AOS2222",
      variant_barcode: "2900000986657",
      product_type: "normal",
      quantity: 10,
      price: 300000,
      amount: 3000000,
      discount_items: [],
      note: "",
      variant_image: "",
      unit: "piece",
      warranty: "",
      tax_rate: null,
      tax_include: null,
      is_composite: null,
      line_amount_after_line_discount: 3000000,
      discount_rate: 0,
      discount_value: 0,
      discount_amount: 0,
      position: 1,
      weight: 2000,
      weight_unit: "g",
      type: "normal",
    },
  ],
  discounts: [
    {
      id: 83925,
      code: "c81980fd-181f-457c-99fc-ad0a07a4ea4b",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T04:53:29Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T04:53:29Z",
      rate: 1,
      value: 32000,
      amount: 32000,
      promotion_id: 1592,
      discount_code: null,
      source: null,
      reason: "đơn hàng 4",
      order_id: 21903828,
    },
  ],
  pre_payments: null,
  payments: [
    {
      id: 125425,
      code: "b10f847b-c0fc-4357-b058-63f7fb085e0b",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T04:53:46Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T04:53:46Z",
      fulfillment_id: null,
      payment_method_id: 0,
      payment_method_code: "cod",
      payment_method: "COD",
      amount: 3199000,
      reference: null,
      source: "cod",
      paid_amount: 3199000,
      return_amount: 0,
      status: "paid",
      customer_id: null,
      type: "cod",
      invoice_id: null,
      note: null,
      point: null,
      bank_account_id: null,
      bank_account_number: null,
      bank_account_holder: null,
      bank_code: null,
      bank_name: null,
      ref_transaction_code: null,
      pay_url: null,
      short_link: null,
      expired_at: null,
    },
  ],
  fulfillments: [
    {
      id: 149416,
      code: "FM000149416",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T04:53:29Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T04:53:46Z",
      order_id: 21903828,
      account_code: "YD15143T",
      assignee_code: "YD15143T",
      delivery_type: "",
      status: "shipped",
      partner_status: null,
      shipment: {
        id: 73790,
        code: "63067cdd-0d05-4e5e-9d1b-2646461b139c",
        version: 1,
        created_by: "YD15143T",
        created_name: "Thoa Test",
        created_date: "2022-10-13T04:53:29Z",
        updated_by: "YD15143T",
        updated_name: "Thoa Test",
        updated_date: "2022-10-13T04:53:29Z",
        delivery_service_provider_id: 2,
        delivery_service_provider_code: "ghtk",
        delivery_service_provider_name: "Giao hàng tiết kiệm",
        delivery_service_provider_type: "external_service",
        delivery_transport_type: "Đường bộ",
        delivery_service_note: null,
        handover_id: null,
        service: "road",
        who_paid: null,
        fee_type: "",
        fee_base_on: "",
        delivery_fee: null,
        reference_status: "",
        reference_status_explanation: "",
        cancel_reason: "",
        tracking_code: "300364366",
        tracking_url: "",
        received_date: null,
        expected_received_date: null,
        shipping_fee_paid_to_three_pls: 145005,
        sender_address_id: 2,
        sender_address:
          '{"id":2,"code":"YDVNHTH01","name":"YODY Đức Thọ","rank":17,"rank_name":"MINI-1","square":120.0,"country_id":233,"country_name":"VIETNAM","city_id":24,"city_name":"Tỉnh Hải Dương","status":"active","status_name":"Đang hoạt động","zip_code":null,"district_id":290,"district_name":"Huyện Thanh Miện","ward_id":4002,"ward_name":"Xã Tân Trào","address":"Từ Ô, Tân Trào, Thanh Miện District, Hai Duong, Vietnam","hotline":"0888586259","manager_code":null,"vm_code":null,"finder_code":null,"mail":null,"number_of_account":null,"reference_id":110339}',
        requirements: "open_try",
        requirements_name: null,
        note_to_shipper:
          "Cho xem và thử hàng, Nếu khách không nhận hàng thì tuyệt đối không thu phí ship của khách.",
        fulfillment_id: 149416,
        cod: 3199000,
        shipper_code: "",
        shipper_name: "Tạ Như Hưng",
        pushing_note: "Chờ đẩy thông tin đơn hàng",
        pushing_status: "waiting",
        shipping_address:
          '{"created_by":"import","created_name":"import","updated_by":"import","updated_name":"import","request_id":null,"operator_kc_id":null,"id":51846,"name":"Nguyễn","email":null,"phone":"0988467460","second_phone":"","country_id":233,"country":null,"city_id":1,"city":"TP. Hà Nội","district_id":1,"district":"Quận Thanh Xuân","ward_id":2,"ward":"Phường Khương Đình","zip_code":null,"full_address":"120 Hoàng Hoa Thám"}',
        office_time: null,
        shipper_phone: "0123456688",
        recipient_sort_code: null,
        info_shipper: " - Tạ Như Hưng - 0123456688",
        type_shipment: null,
      },
      billing_address_id: null,
      items: [
        {
          id: 185607,
          code: "01f23cf3-c5be-4a49-b226-c8345678c6b3",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T04:53:29Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T04:53:29Z",
          order_line_item_id: 229241,
          product_id: 59727,
          product: "Áo Chống Nắng",
          product_code: "MAI1234",
          variant_id: 98539,
          variant:
            "Áo Chống Nắng - Đỏ - Xl1 Vụ Việc Xảy Ra Tại Công Ty Cổ Phần Tập Đoàn Đầu Tư An Đông (liên Quan Bắt Chủ Tịch Tập Đoàn Vạn Thịnh Phát) Và Các Tổ Chức, Đơn Vị Có Liên Quan Đang Được Xã Hội, Người Dân Rất Quan Tâm.",
          order_line_item_note: null,
          quantity: 1,
          base_price: null,
          discount_rate: 0,
          discount_value: 0,
          tax_type_id: null,
          tax_rate: 10,
          line_amount: null,
          line_discount_amount: null,
          line_amount_after_line_discount: 200000,
          weight: 24,
          weight_unit: "g",
          sku: "MAI1234-DDO-XL1",
          variant_barcode: "2900000985391",
          unit: "piece",
        },
        {
          id: 185608,
          code: "4e3bf337-f66d-4cc8-95e7-ccbecb593350",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T04:53:29Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T04:53:29Z",
          order_line_item_id: 229242,
          product_id: 59771,
          product: "Áo Chống Nắng Yooody",
          product_code: "AOS2222",
          variant_id: 98665,
          variant: "Áo Chống Nắng Yooody",
          order_line_item_note: null,
          quantity: 10,
          base_price: null,
          discount_rate: 0,
          discount_value: 0,
          tax_type_id: null,
          tax_rate: null,
          line_amount: null,
          line_discount_amount: null,
          line_amount_after_line_discount: 3000000,
          weight: 2000,
          weight_unit: "g",
          sku: "AOS2222",
          variant_barcode: "2900000986657",
          unit: "piece",
        },
      ],
      stock_location_id: 2,
      returned_store_id: 383,
      payment_status: "",
      total: 3231000,
      total_tax: null,
      total_discount: 0,
      total_quantity: 11,
      stock_out_account_code: null,
      receive_account_code: null,
      cancel_account_code: null,
      receive_cancellation_account_code: null,
      payments: null,
      picked_on: "2022-10-13T04:53:33.000+00:00",
      packed_on: "2022-10-13T04:53:38.000+00:00",
      shipped_on: "2022-10-13T04:53:46.000+00:00",
      export_on: "2022-10-13T04:53:41.000+00:00",
      received_on: null,
      cancel_date: null,
      return_status: "unreturned",
      receive_cancellation_on: null,
      status_before_cancellation: null,
      discount_rate: null,
      discount_value: null,
      discount_amount: null,
      total_line_amount_after_line_discount: 3200000,
      returning_on: null,
      sub_reason_id: null,
      reason_id: null,
      reason_name: null,
      sub_reason_detail_id: null,
      sub_reason_name: null,
      sub_reason_detail_name: null,
    },
  ],
  currency: "VND",
  billing_address: null,
  shipping_address: null,
  shipping_fee_informed_to_customer: 31000,
  url: "",
  sub_status_id: 8,
  sub_status_code: "shipped",
  sub_status: "Thành công",
  order_returns: [
    {
      id: 12534,
      code: "SRN000012534",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T04:55:29Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T04:55:29Z",
      order_id: 21903828,
      order_code: "SO021903828",
      order_exchange_id: null,
      reference_code: "",
      company_id: 1,
      company: "Công ty cổ phần thời trang YODY",
      store_id: 2,
      store: "YODY Đức Thọ",
      store_phone_number: "18002086",
      store_full_address: "Từ Ô, Tân Trào, Thanh Miện District, Hai Duong, Vietnam",
      returned_store_id: null,
      status: "finished",
      price_type: "retail_price",
      tax_treatment: "inclusive",
      source_id: 257,
      source: "test chicken 14",
      note: "",
      tags: "",
      customer_id: 7097265,
      customer: "Nguyễn",
      customer_email: null,
      customer_phone_number: "0988467460",
      payment_method_id: null,
      payment_method: null,
      expected_payment_method_id: null,
      expected_delivery_provider_id: null,
      expected_delivery_type: null,
      customer_note: "",
      sale_note: null,
      account_code: "YD15143T",
      account: "Thoa Test",
      assignee_code: "YD15143T",
      assignee: "Thoa Test",
      channel_id: 13,
      channel: "Admin",
      payment_status: "unpaid",
      total_line_amount_after_line_discount: 300000,
      total: 297000,
      total_quantities: 1,
      currency: "VND",
      order_discount_rate: null,
      order_discount_value: null,
      discount_reason: null,
      total_discount: 3000,
      total_tax: null,
      finalized_account_code: "YD15143T",
      cancel_account_code: null,
      finish_account_code: null,
      finalized_on: "2022-10-13T04:53:29.000+00:00",
      cancelled_on: null,
      finished_on: "2022-10-13T04:53:46.000+00:00",
      referent: null,
      url: "",
      total_amount: null,
      return_date: "2022-10-13T04:55:29.000+00:00",
      receive_date: null,
      point_refund: 0,
      money_refund: 0,
      marketer_code: null,
      marketer: null,
      other_reason: null,
      reason: {
        id: 7,
        code: "order_return",
        name: "Đổi trả hàng",
      },
      sub_reason: {
        id: 54,
        code: "change_size",
        name: "Đối size sản phẩm",
      },
      billing_address: null,
      shipping_address: {
        id: 51846,
        code: "cfbdfad7-f220-481c-a72c-468166e55bb4",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-14T01:59:04Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-14T01:59:04Z",
        name: "Nguyễn",
        email: null,
        phone: "0988467460",
        second_phone: "",
        country: null,
        city_id: 1,
        city: "TP. Hà Nội",
        district_id: 1,
        district: "Quận Thanh Xuân",
        ward_id: 2,
        ward: "Phường Khương Đình",
        zip_code: null,
        full_address: "120 Hoàng Hoa Thám",
        channel: null,
      },
      items: [
        {
          id: 229243,
          code: "a73b6be0-2c5f-4904-9cd6-13ea14094aad",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T04:55:29Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T04:55:29Z",
          order_line_item_id: 229242,
          sku: "AOS2222",
          variant_id: 98665,
          variant: "Áo Chống Nắng Yooody",
          product_id: 59771,
          product: "Áo Chống Nắng Yooody",
          product_code: "AOS2222",
          variant_barcode: "2900000986657",
          product_type: "normal",
          quantity: 1,
          price: 300000,
          amount: 300000,
          discount_items: [],
          note: "",
          variant_image: "",
          unit: "piece",
          warranty: "",
          tax_rate: null,
          tax_include: null,
          is_composite: null,
          line_amount_after_line_discount: 300000,
          discount_rate: 0,
          discount_value: 0,
          discount_amount: 0,
          position: 1,
          weight: 2000,
          weight_unit: "g",
          type: "normal",
        },
      ],
      payments: [],
      discounts: [
        {
          id: 83926,
          code: "85d2cd20-19f6-41fa-84ae-fc141e38de34",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T04:55:29Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T04:55:29Z",
          rate: 1,
          value: 3000,
          amount: 3000,
          promotion_id: null,
          discount_code: null,
          source: null,
          reason: null,
          order_id: -1,
        },
      ],
      money_amount: 297000,
      received: false,
      sub_reason_id: 54,
      reason_id: 7,
      reason_name: "Đổi trả hàng",
      sub_reason_name: "Đối size sản phẩm",
    },
    {
      id: 12536,
      code: "SRN000012536",
      version: 1,
      created_by: "YD15143T",
      created_name: "Thoa Test",
      created_date: "2022-10-13T06:12:46Z",
      updated_by: "YD15143T",
      updated_name: "Thoa Test",
      updated_date: "2022-10-13T06:12:46Z",
      order_id: 21903828,
      order_code: "SO021903828",
      order_exchange_id: 21903830,
      reference_code: "",
      company_id: 1,
      company: "Công ty cổ phần thời trang YODY",
      store_id: 9,
      store: "YODY Vụ Bản",
      store_phone_number: "0836515258",
      store_full_address: "Yody Vụ Bản - Thị Trấn Gôi - Vụ Bản - Nam Định",
      returned_store_id: 9,
      status: "finished",
      price_type: "retail_price",
      tax_treatment: "inclusive",
      source_id: 257,
      source: "test chicken 14",
      note: "",
      tags: null,
      customer_id: 7097265,
      customer: "Nguyễn",
      customer_email: null,
      customer_phone_number: "0988467460",
      payment_method_id: null,
      payment_method: null,
      expected_payment_method_id: null,
      expected_delivery_provider_id: null,
      expected_delivery_type: null,
      customer_note: "",
      sale_note: null,
      account_code: "YD99999",
      account: "Quản trị viên",
      assignee_code: "YD15143T",
      assignee: "Thoa Test",
      channel_id: 13,
      channel: "Admin",
      payment_status: "partial_paid",
      total_line_amount_after_line_discount: 2900000,
      total: 2871000,
      total_quantities: 10,
      currency: "VND",
      order_discount_rate: null,
      order_discount_value: null,
      discount_reason: null,
      total_discount: 29000,
      total_tax: null,
      finalized_account_code: "YD15143T",
      cancel_account_code: null,
      finish_account_code: null,
      finalized_on: "2022-10-13T04:53:29.000+00:00",
      cancelled_on: null,
      finished_on: "2022-10-13T04:53:46.000+00:00",
      referent: null,
      url: "",
      total_amount: null,
      return_date: "2022-10-13T06:12:45.000+00:00",
      receive_date: "2022-10-13T06:12:45.000+00:00",
      point_refund: 0,
      money_refund: 417210,
      marketer_code: null,
      marketer: null,
      other_reason: null,
      reason: {
        id: 7,
        code: "order_return",
        name: "Đổi trả hàng",
      },
      sub_reason: {
        id: 54,
        code: "change_size",
        name: "Đối size sản phẩm",
      },
      billing_address: null,
      shipping_address: {
        id: 51846,
        code: "cfbdfad7-f220-481c-a72c-468166e55bb4",
        version: 1,
        created_by: "YD99999",
        created_name: "Quản trị viên",
        created_date: "2022-10-14T01:59:04Z",
        updated_by: "YD99999",
        updated_name: "Quản trị viên",
        updated_date: "2022-10-14T01:59:04Z",
        name: "Nguyễn",
        email: null,
        phone: "0988467460",
        second_phone: "",
        country: null,
        city_id: 1,
        city: "TP. Hà Nội",
        district_id: 1,
        district: "Quận Thanh Xuân",
        ward_id: 2,
        ward: "Phường Khương Đình",
        zip_code: null,
        full_address: "120 Hoàng Hoa Thám",
        channel: null,
      },
      items: [
        {
          id: 229246,
          code: "dbe22a2d-983a-4e2a-91e2-b1695f444b56",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T06:12:46Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T06:12:46Z",
          order_line_item_id: 229241,
          sku: "MAI1234-DDO-XL1",
          variant_id: 98539,
          variant:
            "Áo Chống Nắng - Đỏ - Xl1 Vụ Việc Xảy Ra Tại Công Ty Cổ Phần Tập Đoàn Đầu Tư An Đông (liên Quan Bắt Chủ Tịch Tập Đoàn Vạn Thịnh Phát) Và Các Tổ Chức, Đơn Vị Có Liên Quan Đang Được Xã Hội, Người Dân Rất Quan Tâm.",
          product_id: 59727,
          product: "Áo Chống Nắng",
          product_code: "MAI1234",
          variant_barcode: "2900000985391",
          product_type: "normal",
          quantity: 1,
          price: 200000,
          amount: 200000,
          discount_items: [],
          note: "",
          variant_image:
            "https://np-cdn.yody.io/images/variant/2022-10-10-10-22-06_a96ed57f-0e27-4048-ac36-62153ba60c60.jpg",
          unit: "piece",
          warranty: "wash-60-mild;wash-70;",
          tax_rate: 10,
          tax_include: null,
          is_composite: null,
          line_amount_after_line_discount: 200000,
          discount_rate: 0,
          discount_value: 0,
          discount_amount: 0,
          position: 2,
          weight: 24,
          weight_unit: "g",
          type: "normal",
        },
        {
          id: 229247,
          code: "1b27d6fc-fa25-4689-9960-642b53ccdd95",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T06:12:46Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T06:12:46Z",
          order_line_item_id: 229242,
          sku: "AOS2222",
          variant_id: 98665,
          variant: "Áo Chống Nắng Yooody",
          product_id: 59771,
          product: "Áo Chống Nắng Yooody",
          product_code: "AOS2222",
          variant_barcode: "2900000986657",
          product_type: "normal",
          quantity: 9,
          price: 300000,
          amount: 2700000,
          discount_items: [],
          note: "",
          variant_image: "",
          unit: "piece",
          warranty: "",
          tax_rate: null,
          tax_include: null,
          is_composite: null,
          line_amount_after_line_discount: 2700000,
          discount_rate: 0,
          discount_value: 0,
          discount_amount: 0,
          position: 1,
          weight: 2000,
          weight_unit: "g",
          type: "normal",
        },
      ],
      payments: [
        {
          id: 125428,
          code: "9f4b00a1-ae6e-4989-9af1-4848db37a1d8",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T06:12:46Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T06:12:46Z",
          fulfillment_id: null,
          payment_method_id: 0,
          payment_method_code: "exchange",
          payment_method: "Đổi hàng",
          amount: 417210,
          reference: "",
          source: "",
          paid_amount: 417210,
          return_amount: 0,
          status: "paid",
          customer_id: null,
          type: "",
          invoice_id: null,
          note: null,
          point: null,
          bank_account_id: null,
          bank_account_number: null,
          bank_account_holder: null,
          bank_code: null,
          bank_name: null,
          ref_transaction_code: null,
          pay_url: null,
          short_link: null,
          expired_at: null,
        },
      ],
      discounts: [
        {
          id: 83929,
          code: "b0afe256-5ee7-4a9a-a458-a60f18e355b4",
          version: 1,
          created_by: "YD15143T",
          created_name: "Thoa Test",
          created_date: "2022-10-13T06:12:46Z",
          updated_by: "YD15143T",
          updated_name: "Thoa Test",
          updated_date: "2022-10-13T06:12:46Z",
          rate: 1,
          value: 29000,
          amount: 29000,
          promotion_id: null,
          discount_code: null,
          source: null,
          reason: null,
          order_id: -1,
        },
      ],
      money_amount: 2871000,
      received: true,
      sub_reason_id: 54,
      reason_id: 7,
      reason_name: "Đổi trả hàng",
      sub_reason_name: "Đối size sản phẩm",
    },
  ],
  accumulate_point: null,
  linked_order_code: null,
  ecommerce_shop_id: null,
  ecommerce_shop_name: null,
  order_migration_id: null,
  created_on: "2022-10-13T04:53:29.000+00:00",
  campaign_id: null,
  utm_tracking: null,
  export_bill: false,
  migration_note: null,
  atomic_migration: false,
  actual_quantity: 11,
  uniform: false,
  sub_reason_id: null,
  reason_id: null,
  reason_name: null,
  automatic_discount: true,
  sub_reason_name: null,
};
handleFixWindowMatchMediaTest();
const setup = () => {
  render(<OrderFulfillmentShowProduct orderDetail={orderDetailDataTest} />);
};

describe("OrderFulfillmentShowProduct", () => {
  setup();
  it("production quantity", async () => {
    const productQuantityElement = document.querySelector(
      "#order_fulfillment_production > div > div > div > div > div > b",
    );

    const quantity = orderDetailDataTest.items.reduce(
      (a: any, b: any) => Number(a.quantity) + Number(b.quantity),
    );
    expect(productQuantityElement?.innerHTML).toMatch(quantity.toString());
  });

  it("list product", async () => {
    await waitFor(() => {
      //   const showProduct: any = document.querySelector(
      //     "#order_fulfillment_production > div > div > div.ant-collapse-header > span",
      //   );
      //   showProduct?.click();
      const listProductElement = document.querySelector(
        "#order_fulfillment_production > div > div > div.ant-collapse-content.ant-collapse-content-active > div",
      );
      if (listProductElement) {
        expect(listProductElement).toBeTruthy();
        const listProductArray = Array.prototype.slice.call(listProductElement?.children);

        expect(listProductArray.length).toBe(orderDetailDataTest.items.length);
      }
    });
  });
});
